To demonstrate the high technicality required for an ICML submission, we must move beyond "what" the blocks do and explain the mathematical and algorithmic mechanisms that make them novel. Standard RAG (Retrieval-Augmented Generation) is insufficient because it cannot handle the multi-dimensional complexity of 10 years of personal history or the semantic gap between pixels and abstract preferences.
The following breakdown emphasizes why these mechanisms are non-obvious and technically rigorous.
Block 1: Saliency-Triggered Temporal GGNN
The Challenge: 10 years of a Personal Knowledge Graph (PKG) contains millions of nodes. Standard graph retrieval suffers from "relational noise," where similar but irrelevant nodes (e.g., every coffee the user ever drank) interfere with the specific context.
 * Saliency-Triggered Pruning: We do not perform a keyword search. Instead, the Gating Signal is a high-dimensional vector derived from the visual saliency of the input image. This signal acts as a masking function over the graph’s adjacency matrix, performing hard-pruning of subgraphs that are semantically orthogonal to the observed visual entities before any message passing occurs.
 * Temporal-Identity Gating: Within the Gated Graph Neural Network (GGNN), the Update Gate (\mathbf{z}_t) is modified to include a Temporal Decay Term (\tau) and an Identity Anchor (\alpha).
   * Technicality: Instead of standard GRU-like updates, the hidden state of a node only propagates if it satisfies \sigma(W[\text{anchor}, \text{time\_delta}]) > \text{threshold}. This ensures that "Decaf history" at "Nighttime" is amplified while "Espresso history" from five years ago is suppressed at the latent level.
   * Output: A Constraint Manifold (\mathcal{M})—a bounded subspace in the latent space that represents the "Logical Truths" for that specific user at that specific moment.
Block 2: Manifold Alignment (Geometric Constraint)
The Challenge: Pixels are deceptive; a user might look different due to aging or lighting (Identity Evolution).
 * Projective Alignment: We don't just "feed" KG data to the model. We treat the Constraint Manifold (\mathcal{M}) as a geometric prior.
 * Technical Mechanism: The raw visual tokens (V_{raw}) are projected into a shared embedding space. We calculate the Semantic Orthogonality Score between the visual features and the manifold.
   * Technicality: If the visual features of "Red Wine" are detected, but the manifold \mathcal{M} (based on "disliked items") shows that the user hates red wine, the alignment layer applies a vector projection that shifts the visual embedding toward the "Gift" node in the manifold. This forces the model to "see" the wine as an anomaly/gift rather than a personal preference.
Block 3: Abductive Cformer (MCCA)
The Challenge: Standard Cross-Attention only cares about visual similarity. It doesn't know why a specific visual detail (like a "Decaf" label) is more important than a "Shiny Mug".
 * Context-Seeded Query (Q_{seed}): Queries are not learned parameters; they are dynamically generated by fusing the User Query (Q) with the Personal Context Vector (C_{pers}) using a non-linear MLP.
 * Manifold-Constrained Cross-Attention (MCCA): This is the core technical contribution.
   * The Math: The attention score A is typically \text{Softmax}(QK^T/\sqrt{d}). We introduce a Constraint Penalty: A = \text{Softmax}(\frac{QK^T}{\sqrt{d}} - \lambda \cdot \text{dist}(K, \mathcal{M})).
   * Technicality: \lambda is a learnable parameter that scales the distance between a visual token (K) and the nearest point on the truth manifold (\mathcal{M}).
   * Result: Visual tokens that contradict the KG (e.g., "high-caffeine" cues at 11 PM) are mathematically suppressed, while tokens that explain the Abductive Anomaly (e.g., "Decaf Blend" text) are amplified.
Example: "Sarah's Dinner" Red Wine
 * Block 1: The system detects "Red Wine" and "19:00". The GGNN prunes the graph to ignore the user's wine preferences (dislike) but activates the "Calendar: Dinner at Sarah's" node.
 * Block 2: The Manifold Alignment recognizes the anomaly—the user is holding an item they dislike. It projects the visual feature into the "Gift-giving" region of the manifold.
 * Block 3: The MCCA ensures that when the user asks "How is this?", the attention heads ignore the "cherry notes" of the wine and focus on the "Gift" context retrieved from the KG.
 * Block 4: The LLM generates the abductive answer: "Since you don't like red wine but are heading to Sarah's, this is a thoughtful gift".
Would you like me to draft the "Methodology" section of the ICML paper using these formal mathematical definitions?

