# -*- coding: utf-8 -*-
"""data_gpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utTHYyKBKnkeDlwSlmvVEZCxFDqmCgeW
"""

# Re-import everything since kernel was reset
import random
import uuid
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set random seed for reproducibility
random.seed(42)
np.random.seed(42)

START_DATE = datetime(2024, 1, 1)
END_DATE = datetime(2024, 12, 31)
N_USERS = 5

APP_PACKAGES = ['com.instagram.android', 'com.whatsapp', 'com.spotify.music',
                'com.google.android.gm', 'com.twitter.android', 'com.strava', 'com.binance.dev']
SCENE_NAMES = ['beach', 'mountain', 'cityscape', 'market', 'restaurant', 'gym', 'library', 'home', 'office']
LOCATIONS = ['New York', 'San Francisco', 'Austin', 'London', 'Tokyo', 'Paris', 'Delhi']
CONTACT_NAMES = ['Alice', 'Bob', 'Charlie', 'Daisy', 'Eve', 'Frank', 'Grace', 'Heidi']
INTEREST_APPS = {'trading': ['com.binance.dev', 'com.robinhood.android'], 'fitness': ['com.strava', 'com.nike.run']}

def random_date(start, end):
    delta = end - start
    rand_days = random.randint(0, delta.days)
    rand_seconds = random.randint(0, 86400)
    return start + timedelta(days=rand_days, seconds=rand_seconds)

def generate_tpp_timestamps(start_date, end_date, intensity=0.1):
    total_days = (end_date - start_date).days
    timestamps = []
    current = start_date
    while current < end_date:
        interval = np.random.exponential(1.0 / intensity)
        current += timedelta(hours=interval * 24)
        if current < end_date:
            timestamps.append(current)
    return timestamps

def simulate_travel(user_id):
    travel_phases, images, app_usages = [], [], []
    for i in range(2):
        travel_start = random_date(START_DATE, END_DATE - timedelta(days=7))
        travel_end = travel_start + timedelta(days=random.randint(3, 7))
        city = random.choice(LOCATIONS)
        scene = random.choice(['beach', 'market', 'temple', 'hiking trail'])
        images.append({
            'user_id': user_id, 'person_id': str(uuid.uuid4()), 'gender': random.choice(['M', 'F']),
            'age': random.randint(20, 50), 'bounding_box': [random.randint(0, 300), random.randint(0, 300), 50, 50],
            'timestamp': travel_start.isoformat(), 'location': city, 'scene_name': scene
        })
        for _ in range(random.randint(10, 25)):
            images.append({
                'user_id': user_id, 'person_id': None, 'gender': None, 'age': None,
                'bounding_box': None, 'timestamp': (travel_start + timedelta(hours=random.randint(0, 120))).isoformat(),
                'location': city, 'scene_name': random.choice(SCENE_NAMES)
            })
        for _ in range(random.randint(20, 50)):
            app_usages.append({
                'user_id': user_id, 'timestamp': (travel_start + timedelta(hours=random.randint(0, 120))).isoformat(),
                'duration': random.randint(30, 600), 'package_name': random.choice(APP_PACKAGES),
                'event_type': random.choice(['foreground', 'background']), 'time_zone': 'UTC+0'
            })
        travel_phases.append({
            'user_id': user_id, 'start_date': travel_start.isoformat(),
            'end_date': travel_end.isoformat(), 'city': city
        })
    return travel_phases, images, app_usages

def simulate_interest_change(user_id):
    interest_events, interest_images, interest_apps = [], [], []
    interest_day = random_date(START_DATE, END_DATE - timedelta(days=30))
    new_interest = random.choice(list(INTEREST_APPS.keys()))
    trigger_app = random.choice(INTEREST_APPS[new_interest])
    interest_apps.append({
        'user_id': user_id, 'timestamp': interest_day.isoformat(), 'duration': random.randint(60, 300),
        'package_name': trigger_app, 'event_type': 'foreground', 'time_zone': 'UTC+0'
    })
    for _ in range(random.randint(30, 60)):
        interest_apps.append({
            'user_id': user_id, 'timestamp': (interest_day + timedelta(hours=random.randint(0, 240))).isoformat(),
            'duration': random.randint(30, 600), 'package_name': random.choice(INTEREST_APPS[new_interest]),
            'event_type': 'foreground', 'time_zone': 'UTC+0'
        })
    for _ in range(random.randint(5, 15)):
        interest_images.append({
            'user_id': user_id, 'person_id': None, 'gender': None, 'age': None,
            'bounding_box': None, 'timestamp': (interest_day + timedelta(hours=random.randint(0, 240))).isoformat(),
            'location': random.choice(LOCATIONS), 'scene_name': new_interest
        })
    interest_events.append({
        'user_id': user_id, 'interest': new_interest,
        'start_date': interest_day.isoformat(), 'phase': 'growth'
    })
    return interest_events, interest_images, interest_apps

def simulate_normal_data(user_id):
    timestamps = generate_tpp_timestamps(START_DATE, END_DATE, intensity=0.05)
    app_usages = [{
        'user_id': user_id, 'timestamp': t.isoformat(), 'duration': random.randint(20, 300),
        'package_name': random.choice(APP_PACKAGES), 'event_type': random.choice(['foreground', 'background']),
        'time_zone': 'UTC+0'
    } for t in timestamps]
    call_logs = [{
        'user_id': user_id, 'identifier': str(uuid.uuid4()), 'date': t.isoformat(),
        'type': random.choice(['incoming', 'outgoing', 'missed']), 'geocoded_loc': random.choice(LOCATIONS),
        'duration': random.randint(10, 600), 'number': f'+1{random.randint(1000000000, 9999999999)}',
        'contact_id': str(uuid.uuid4()), 'call_rec': None, 'call_rec_transcript': None,
        'ai_summary': None, 'ai_keywords': random.sample(['project', 'meeting', 'personal', 'urgent'], 2),
        'entities': random.sample(CONTACT_NAMES, 2)
    } for t in timestamps]
    return app_usages, call_logs

# Aggregate for all users
users_travel, users_interest = [], []
all_images, all_app_usages, all_call_logs = [], [], []

for uid in range(N_USERS):
    user_id = f"user_{uid}"
    travel_info, travel_imgs, travel_apps = simulate_travel(user_id)
    interest_info, interest_imgs, interest_apps = simulate_interest_change(user_id)
    normal_apps, normal_calls = simulate_normal_data(user_id)
    users_travel.extend(travel_info)
    users_interest.extend(interest_info)
    all_images.extend(travel_imgs + interest_imgs)
    all_app_usages.extend(normal_apps + travel_apps + interest_apps)
    all_call_logs.extend(normal_calls)

# Convert to DataFrames
df_travel = pd.DataFrame(users_travel)
df_interest = pd.DataFrame(users_interest)
df_images = pd.DataFrame(all_images)
df_apps = pd.DataFrame(all_app_usages)
df_calls = pd.DataFrame(all_call_logs)

df_travel.head(), df_interest.head(), df_images.head(), df_apps.head(), df_calls.head()

import random
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Update df_images to include new location format: lat, lon, city, state, country

# Sample function to generate locations with extended info
def generate_location_with_metadata():
    cities_info = [
        ("New York", "NY", "USA", 40.7128, -74.0060),
        ("San Francisco", "CA", "USA", 37.7749, -122.4194),
        ("Paris", "IDF", "France", 48.8566, 2.3522),
        ("Tokyo", "Tokyo", "Japan", 35.6895, 139.6917),
        ("London", "ENG", "UK", 51.5074, -0.1278),
        ("Berlin", "BE", "Germany", 52.5200, 13.4050),
        ("Mumbai", "MH", "India", 19.0760, 72.8777),
        ("Sydney", "NSW", "Australia", -33.8688, 151.2093)
    ]
    city, state, country, lat, lon = random.choice(cities_info)
    return {
        'lat': round(lat + random.uniform(-0.01, 0.01), 6),
        'lon': round(lon + random.uniform(-0.01, 0.01), 6),
        'city': city,
        'state': state,
        'country': country
    }

# Modify df_images location field
def update_image_locations(df_images):
    updated_locations = []
    for _ in range(len(df_images)):
        loc = generate_location_with_metadata()
        updated_locations.append(loc)
    df_images['location'] = updated_locations
    return df_images

# Apply the update
df_images_updated = update_image_locations(df_images)
df_images_updated.head()

import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# Convert timestamp fields to datetime
df_images['timestamp'] = pd.to_datetime(df_images['timestamp'])
df_apps['timestamp'] = pd.to_datetime(df_apps['timestamp'], format='mixed')
df_calls['date'] = pd.to_datetime(df_calls['date'])
# df_calendar['start_date'] = pd.to_datetime(df_calendar['start_date'])

# Combine data into a single timeline per modality for counts
def get_daily_counts(df, time_col, label):
    return df.groupby(df[time_col].dt.date).size().rename(label)

image_counts = get_daily_counts(df_images, 'timestamp', 'Images')
app_counts = get_daily_counts(df_apps, 'timestamp', 'App Usage')
call_counts = get_daily_counts(df_calls, 'date', 'Call Logs')
# calendar_counts = get_daily_counts(df_calendar, 'start_date', 'Calendar Events')

# Merge all counts into one DataFrame
# activity_counts = pd.concat([image_counts, app_counts, call_counts, calendar_counts], axis=1).fillna(0)
activity_counts = pd.concat([image_counts, app_counts, call_counts], axis=1).fillna(0)

# Plotting
plt.figure(figsize=(16, 6))
sns.lineplot(data=activity_counts)
plt.title('Daily Activity Count per Modality Over Time')
plt.xlabel('Date')
plt.ylabel('Activity Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(True)
plt.show()

