# -*- coding: utf-8 -*-
"""DSE_aggregate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g89pXfgTU5UTKjlNRf98Qccsw8S6vBZ_
"""

!pip install torch torch_geometric numpy scikit-learn matplotlib
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
from math import sin, cos, pi
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import random
from tqdm import tqdm

# Attempt to import PyTorch Geometric, provide instructions if missing
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv, global_mean_pool
except ImportError:
    print("PyTorch Geometric not found.")
    print("Please install it by following the instructions at: https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html")
    # exit()

# --- 1. Configuration & Constants ---

# General Config
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_DAYS_PER_ACTIVITY = 50 # Reduced for faster simulation
EPOCHS_TEMPORAL = 50
EPOCHS_GRAPH = 50
BETA_KL = 0.5 # Weight for KL divergence in loss

# Temporal Model Config
T_INPUT_DIM = 5
T_HIDDEN_DIM = 64
T_LATENT_DIM = 16 # E_temporal_spread dimension
T_MAX_SEQ_LEN = 150
T_NUM_HIST_BINS = 24

# Graph Model Config
G_EMBEDDING_DIM = 64
G_LATENT_DIM = 32 # E_social_activity dimension
G_NUM_HAN_LAYERS = 2
NODE_FEATURE_DIM = 32 # Simulated feature dimension for nodes

# --- 2. Data Simulation (Temporal + Graph) ---

# Node and Edge types for the graph
NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log'),
    ('activity_log', 'related_to', 'scene')
]

# Simulated feature pools for graph nodes
# In a real scenario, these would come from other models (e.g., FaceNet, ResNet)
PERSON_FEATURES = {f"person_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(20)}
SCENE_FEATURES = {f"scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(10)}
ACTIVITY_LOG_FEATURES = {f"log_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(5)}


def generate_daily_data():
    """Generates both temporal and graph data for various activities."""
    activities = {
        "morning_walk": {
            "time_gen": lambda: np.random.normal(loc=420, scale=30, size=np.random.randint(15, 30)),
            "graph_gen": lambda: generate_graph_for_activity("morning_walk")
        },
        "work_day": {
            "time_gen": lambda: np.concatenate([
                np.random.normal(loc=540, scale=15, size=np.random.randint(20, 40)),
                np.random.normal(loc=840, scale=10, size=np.random.randint(10, 20)),
                np.random.normal(loc=1020, scale=20, size=np.random.randint(20, 40)),
            ]),
            "graph_gen": lambda: generate_graph_for_activity("work_day")
        },
        "family_event": {
            "time_gen": lambda: np.random.normal(loc=1080, scale=60, size=np.random.randint(40, 80)),
            "graph_gen": lambda: generate_graph_for_activity("family_event")
        },
        "errands_day": {
            "time_gen": lambda: np.random.uniform(600, 960, size=np.random.randint(30, 50)),
            "graph_gen": lambda: generate_graph_for_activity("errands_day")
        }
    }

    activity_names = sorted(list(activities.keys()))
    label_to_idx = {name: i for i, name in enumerate(activity_names)}

    all_temporal_data = []
    all_graph_data = []
    all_labels = []

    print("Generating simulated daily data...")
    for label_name in tqdm(activity_names):
        activity = activities[label_name]
        for _ in range(NUM_DAYS_PER_ACTIVITY):
            # Generate temporal data
            ts = activity["time_gen"]()
            ts = np.clip(ts, 0, 1439)
            ts = sorted(ts)

            # Generate corresponding graph data
            graph = activity["graph_gen"]()

            all_temporal_data.append(ts)
            all_graph_data.append(graph)
            all_labels.append(label_to_idx[label_name])

    return all_temporal_data, all_graph_data, all_labels, activity_names

def generate_graph_for_activity(activity_name):
    """Simulates a plausible graph for a given activity."""
    data = HeteroData()

    if activity_name == "morning_walk":
        # Nodes: User + 1 random person, 1-2 outdoor scenes, few photo logs
        persons = ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 1)
        scenes = random.sample([s for s in SCENE_FEATURES], 2)
        logs = random.sample([l for l in ACTIVITY_LOG_FEATURES], 2)

        data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
        data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
        data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])

        # Edges
        data['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0], [1]], dtype=torch.long)
        data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1], [0, 1]], dtype=torch.long)
        data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0, 0], [0, 1]], dtype=torch.long)
        data['activity_log', 'related_to', 'scene'].edge_index = torch.tensor([[0, 1], [0, 1]], dtype=torch.long)

    elif activity_name == "work_day":
        # Nodes: User + 2 colleagues, 1 home & 1 office scene, many logs
        persons = ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 2)
        scenes = ['scene_0', 'scene_1'] # Home, Office
        logs = random.sample([l for l in ACTIVITY_LOG_FEATURES], 4)

        data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
        data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
        data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])

        # Edges (user interacts with colleagues at office)
        data['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0, 0], [1, 2]], dtype=torch.long)
        data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1, 2], [0, 1, 1]], dtype=torch.long) # User@Home, All@Office
        data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0, 0, 0, 0], [0, 1, 2, 3]], dtype=torch.long)
        data['activity_log', 'related_to', 'scene'].edge_index = torch.tensor([[0, 1, 2, 3], [1, 1, 1, 1]], dtype=torch.long) # All logs at office

    elif activity_name == "family_event":
        # Nodes: User + 4 family members, 1 event scene, many logs
        persons = ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 4)
        scenes = random.sample([s for s in SCENE_FEATURES], 1)
        logs = random.sample([l for l in ACTIVITY_LOG_FEATURES], 3)

        data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
        data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
        data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])

        # Edges (everyone interacts)
        edges = [[i, j] for i in range(5) for j in range(5) if i != j]
        data['person', 'interacts_with', 'person'].edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
        data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[p_idx, 0] for p_idx in range(5)], dtype=torch.long).t().contiguous()
        data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0, 1, 2], [0, 1, 2]], dtype=torch.long)
        data['activity_log', 'related_to', 'scene'].edge_index = torch.tensor([[0, 1, 2], [0, 0, 0]], dtype=torch.long)

    elif activity_name == "errands_day":
        # Nodes: User, 3-4 different scenes, various logs
        persons = ['person_0']
        scenes = random.sample([s for s in SCENE_FEATURES], 4)
        logs = random.sample([l for l in ACTIVITY_LOG_FEATURES], 3)

        data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
        data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
        data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])

        data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 0, 0, 0], [0, 1, 2, 3]], dtype=torch.long)
        data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0, 0, 0], [0, 1, 2]], dtype=torch.long)
        data['activity_log', 'related_to', 'scene'].edge_index = torch.tensor([[0, 1, 2], [0, 1, 2]], dtype=torch.long)

    # Ensure all node/edge types are defined, even if empty
    for n_type in NODE_TYPES:
        if n_type not in data.node_types:
            data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)
    for e_type in EDGE_TYPES:
        if e_type not in data.edge_types:
            data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)

    return data

# --- 3. Model Definitions ---

# --- Temporal Spread Model ---
class TemporalDataset(Dataset):
    def __init__(self, daily_data, max_seq_len, num_hist_bins=24):
        self.daily_data = daily_data
        self.max_seq_len = max_seq_len
        self.num_hist_bins = num_hist_bins

    def __len__(self):
        return len(self.daily_data)

    def create_hourly_histogram(self, timestamps_minutes):
        hist, _ = np.histogram(timestamps_minutes, bins=np.linspace(0, 1440, self.num_hist_bins + 1))
        return hist / (np.sum(hist) + 1e-9)

    def __getitem__(self, idx):
        timestamps = self.daily_data[idx]
        features = []
        if timestamps:
            prev_time = 0
            for t in timestamps:
                hour, minute_of_hour = t // 60, t % 60
                features.append([
                    sin(2 * pi * hour / 24), cos(2 * pi * hour / 24),
                    sin(2 * pi * minute_of_hour / 60), cos(2 * pi * minute_of_hour / 60),
                    (t - prev_time) / 1440.0
                ])
                prev_time = t

        if len(features) > self.max_seq_len:
            features = features[:self.max_seq_len]
        else:
            features.extend([[0.0] * 5 for _ in range(self.max_seq_len - len(features))])

        histogram = self.create_hourly_histogram(timestamps)
        return torch.tensor(features, dtype=torch.float32), torch.tensor(histogram, dtype=torch.float32)

class TemporalSpreadVGAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, output_dim, num_layers=2):
        super(TemporalSpreadVGAE, self).__init__()
        self.encoder_rnn = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)
        self.fc_mu = nn.Linear(hidden_dim * 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim * 2, latent_dim)
        self.decoder_fc = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim), nn.ReLU(),
            nn.Linear(hidden_dim, output_dim), nn.Softmax(dim=-1)
        )

    def encode(self, x):
        _, (hidden, _) = self.encoder_rnn(x)
        hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1)
        return self.fc_mu(hidden), self.fc_logvar(hidden)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        return self.decoder_fc(z)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

# --- Whom/Where/Activity (Graph) Model ---
class DSENVGAE(nn.Module):
    def __init__(self, node_feature_dim, embedding_dim, latent_dim, num_layers, metadata):
        super(DSENVGAE, self).__init__()
        self.latent_dim = latent_dim
        self.metadata = metadata

        # Encoder
        self.lin_dict = nn.ModuleDict({
            node_type: nn.Linear(node_feature_dim, embedding_dim) for node_type in metadata[0]
        })
        self.han_convs = nn.ModuleList([
            HANConv(embedding_dim, embedding_dim, metadata=metadata, heads=4) for _ in range(num_layers)
        ])
        self.mu_linear = nn.Linear(embedding_dim, latent_dim)
        self.logvar_linear = nn.Linear(embedding_dim, latent_dim)

    def encode(self, data):
        x_dict = {
            node_type: self.lin_dict[node_type](x) for node_type, x in data.x_dict.items()
        }
        for conv in self.han_convs:
            x_dict = conv(x_dict, data.edge_index_dict)

        # Mean pooling across all nodes of all types to get graph embedding
        pooled_embeddings = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]
        if not pooled_embeddings:
            # Return zeros for an empty or invalid graph
            pooled_mean = torch.zeros(G_EMBEDDING_DIM, device=DEVICE)
        else:
            pooled_mean = torch.stack(pooled_embeddings).mean(dim=0)

        mu = self.mu_linear(pooled_mean)
        log_var = self.logvar_linear(pooled_mean)
        return mu, log_var, x_dict

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, h_dict, edge_index_dict):
        """
        Calculates link reconstruction loss.
        z: The latent vector for the graph. Not directly used here, but part of VAE structure.
        h_dict: The dictionary of node embeddings from the encoder.
        edge_index_dict: The ground-truth edges of the graph.
        """
        link_recon_loss = 0
        num_edge_types_processed = 0

        # Iterate through the ground-truth edge types
        for edge_type, edge_index in edge_index_dict.items():
            if edge_index.numel() == 0:
                continue

            num_edge_types_processed += 1
            src_type, _, dst_type = edge_type

            # Get embeddings for the source and destination nodes of existing ("positive") edges
            pos_src_indices = edge_index[0]
            pos_dst_indices = edge_index[1]
            pos_src_embeds = h_dict[src_type][pos_src_indices]
            pos_dst_embeds = h_dict[dst_type][pos_dst_indices]

            # Calculate score for positive edges (dot product similarity)
            pos_score = (pos_src_embeds * pos_dst_embeds).sum(dim=-1)

            # Negative sampling: randomly sample destination nodes
            num_dst_nodes_total = h_dict[dst_type].size(0)
            neg_dst_indices = torch.randint(0, num_dst_nodes_total, (len(pos_dst_indices),), device=z.device)
            neg_dst_embeds = h_dict[dst_type][neg_dst_indices]

            neg_score = (pos_src_embeds * neg_dst_embeds).sum(dim=-1)

            # Using Binary Positive-unlabeled (BPR) loss as a simple and effective choice
            loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-9).mean()
            link_recon_loss += loss

        # Average the loss over the number of edge types present in the graph
        return link_recon_loss / (num_edge_types_processed + 1e-9)

    def forward(self, data):
        # The forward pass runs the encoder to get latent variables and node embeddings
        mu, logvar, h_dict = self.encode(data)
        return mu, logvar, h_dict

    def loss(self, mu, logvar, h_dict, original_data, beta):
        """
        Calculates the total loss for the VAE.
        """
        # Reparameterize to get the latent vector z
        z = self.reparameterize(mu, logvar)

        # Calculate the reconstruction loss by calling the decoder
        # The decoder now receives the correct dictionaries it needs
        link_recon_loss = self.decode(z, h_dict, original_data.edge_index_dict)

        # Calculate the KL Divergence
        kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

        # Combine the losses
        total_loss = link_recon_loss + beta * kl_loss
        return total_loss

# --- 4. Training and Evaluation ---

def train_temporal_model(data, epochs):
    print("\n--- Training Temporal Spread VAE ---")
    dataset = TemporalDataset(data, T_MAX_SEQ_LEN, T_NUM_HIST_BINS)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)
    model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, T_NUM_HIST_BINS).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    recon_loss_fn = nn.KLDivLoss(reduction='batchmean')

    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for features, histograms in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
            features, histograms = features.to(DEVICE), histograms.to(DEVICE)
            optimizer.zero_grad()
            recon_hist, mu, logvar = model(features)

            recon_loss = recon_loss_fn(torch.log(recon_hist + 1e-9), histograms)
            kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

            loss = recon_loss + BETA_KL * kl_loss / features.size(0) # Normalize KL by batch size
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
    print(f"Temporal VAE training complete. Final Loss: {total_loss / len(dataloader):.4f}")
    return model

def train_graph_model(data, epochs):
    print("\n--- Training Social/Activity (Graph) VAE ---")
    metadata = (NODE_TYPES, EDGE_TYPES)
    model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, metadata).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    model.train()
    for epoch in range(epochs):
        total_loss = 0
        # Training one graph at a time for simplicity
        for graph_data in tqdm(data, desc=f"Epoch {epoch+1}/{epochs}"):
            graph_data = graph_data.to(DEVICE)
            optimizer.zero_grad()
            mu, logvar, h_dict = model(graph_data)
            loss = model.loss(mu, logvar, h_dict, graph_data, BETA_KL)
            if torch.isnan(loss): continue # Skip if loss becomes NaN (can happen with unstable graphs)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
    print(f"Graph VAE training complete. Final Loss: {total_loss / len(data):.4f}")
    return model

def get_embeddings(temporal_model, graph_model, temporal_data, graph_data):
    print("\n--- Extracting and Aggregating Embeddings ---")
    temporal_model.eval()
    graph_model.eval()

    all_temporal_embeddings = []
    all_graph_embeddings = []

    # Using the same Dataset class for temporal data to ensure consistent preprocessing
    temporal_dataset = TemporalDataset(temporal_data, T_MAX_SEQ_LEN, T_NUM_HIST_BINS)

    with torch.no_grad():
        # Get temporal embeddings
        for i in range(len(temporal_dataset)):
            features, _ = temporal_dataset[i]
            features = features.unsqueeze(0).to(DEVICE) # Add batch dimension
            mu, _ = temporal_model.encode(features)
            all_temporal_embeddings.append(mu.cpu().numpy().flatten())

        # Get graph embeddings
        for g_data in tqdm(graph_data, desc="Extracting Graph Embeddings"):
            g_data = g_data.to(DEVICE)
            mu, _ , _ = graph_model.encode(g_data)
            all_graph_embeddings.append(mu.cpu().numpy().flatten())

    # Aggregate by concatenation
    agg_embeddings = np.concatenate([
        np.array(all_temporal_embeddings),
        np.array(all_graph_embeddings)
    ], axis=1)

    return agg_embeddings

def plot_tsne(embeddings, labels, class_names):
    print("\n--- Generating t-SNE Plot ---")
    tsne = TSNE(n_components=2, perplexity=30, n_iter=1000, random_state=42)
    tsne_results = tsne.fit_transform(embeddings)

    plt.figure(figsize=(12, 8))
    scatter = plt.scatter(tsne_results[:, 0], tsne_results[:, 1], c=labels, cmap='viridis', alpha=0.7)
    plt.title('t-SNE of Aggregate Day Dynamics Embeddings', fontsize=16)
    plt.xlabel('t-SNE Dimension 1', fontsize=12)
    plt.ylabel('t-SNE Dimension 2', fontsize=12)

    # Create a legend
    handles, _ = scatter.legend_elements()
    plt.legend(handles=handles, labels=class_names, title="Activity Types")

    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

# --- 5. Main Execution ---
print(f"Using device: {DEVICE}")

# 1. Generate Data
temporal_data, graph_data, labels, activity_names = generate_daily_data()

# 2. Train Models
temporal_model = train_temporal_model(temporal_data, EPOCHS_TEMPORAL)

graph_model = train_graph_model(graph_data, EPOCHS_GRAPH)

# 3. Get Aggregate Embeddings
aggregate_embeddings = get_embeddings(temporal_model, graph_model, temporal_data, graph_data)

# 4. Plot Results
plot_tsne(aggregate_embeddings, labels, activity_names)



"""Robustness test"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
from math import sin, cos, pi
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import random
from tqdm import tqdm
from scipy.spatial.distance import cdist
import matplotlib.colors as mcolors

# Attempt to import PyTorch Geometric
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv
except ImportError:
    print("PyTorch Geometric not found. Please install it.")
    # exit()

# --- 1. Configuration & Constants ---
# General Config
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_DAYS_PER_ACTIVITY = 40 # 40 days for each activity variant
EPOCHS_TEMPORAL = 5
EPOCHS_GRAPH = 5
BETA_KL = 0.5

# Model Configs
T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM = 5, 64, 16
T_MAX_SEQ_LEN, T_NUM_HIST_BINS = 150, 24
G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS = 64, 32, 2
NODE_FEATURE_DIM = 32

# --- 2. Enhanced Data Simulation for Robustness ---

NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log')
]

# Feature pools for nodes, including location-specific scenes
PERSON_FEATURES = {f"person_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(20)}
# Generic scenes + location-specific scenes
SCENE_FEATURES = {
    **{f"generic_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(5)},
    **{f"paris_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(3)},
    **{f"bengaluru_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(3)},
}
ACTIVITY_LOG_FEATURES = {f"log_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(5)}

# --- Graph Generation Helpers ---
def create_walk_graph(is_evening=False):
    data = HeteroData()
    persons = ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 1)
    scenes = random.sample([s for s in SCENE_FEATURES if 'generic' in s], 2)
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1], [0, 1]], dtype=torch.long)
    return data

def create_work_graph(is_solo=False):
    data = HeteroData()
    persons = ['person_0'] if is_solo else ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 2)
    scenes = ['generic_scene_0', 'generic_scene_1'] # Home, Office
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    if not is_solo:
        data['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0, 0], [1, 2]], dtype=torch.long)
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[p_idx, 1] for p_idx in range(len(persons))], dtype=torch.long).t()
    return data


# def create_work_graph(is_solo=False):
#     data = HeteroData()
#     persons = ['person_0'] if is_solo else ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 2)
#     # This line was previously unused, causing the error.
#     scenes = ['scene_0', 'scene_1'] # Home, Office

#     # Assign features to person nodes
#     data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])

#     # FIX: Explicitly assign features to the scene nodes
#     data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])

#     if not is_solo:
#         data['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0, 0], [1, 2]], dtype=torch.long)

#     # Edges now correctly point to scene nodes that have features
#     # (e.g., all persons appear in scene 1, the "Office")
#     data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[p_idx, 1] for p_idx in range(len(persons))], dtype=torch.long).t()
#     return data

def create_travel_graph(location='paris'):
    data = HeteroData()
    persons = ['person_0']
    scene_keys = [s for s in SCENE_FEATURES if location in s]
    scenes = random.sample(scene_keys, 2)
    logs = random.sample(list(ACTIVITY_LOG_FEATURES.keys()), 3)
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 0], [0, 1]], dtype=torch.long)
    data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0,0,0],[0,1,2]], dtype=torch.long)
    return data

def finalize_graph(data):
    # Ensure all node/edge types are defined, even if empty
    for n_type in NODE_TYPES:
        if n_type not in data.node_types:
            data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)
    for e_type in EDGE_TYPES:
        if e_type not in data.edge_types:
            data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)
    return data

def generate_daily_data():
    """Generates temporal and graph data for core activities and robustness tests."""
    activities = {
        "morning_walk": {
            "time_gen": lambda: np.random.normal(loc=420, scale=30, size=30), # 7 AM
            "graph_gen": lambda: create_walk_graph()
        },
        "evening_walk": { # Robustness test: Temporal Shift
            "time_gen": lambda: np.random.normal(loc=1080, scale=30, size=30), # 6 PM
            "graph_gen": lambda: create_walk_graph() # Identical graph structure
        },
        "work_day": {
            "time_gen": lambda: np.concatenate([np.random.normal(loc=570, scale=60, size=40), np.random.normal(loc=900, scale=60, size=40)]),
            "graph_gen": lambda: create_work_graph(is_solo=False)
        },
        "work_day_solo": { # Robustness test: Context Change
            "time_gen": lambda: np.concatenate([np.random.normal(loc=570, scale=60, size=40), np.random.normal(loc=900, scale=60, size=40)]),
            "graph_gen": lambda: create_work_graph(is_solo=True) # Different graph
        },
        "family_event": {
            "time_gen": lambda: np.random.normal(loc=1140, scale=45, size=80), # 7 PM
            "graph_gen": lambda: finalize_graph(HeteroData({
                'person':{'x': torch.stack(random.sample(list(PERSON_FEATURES.values()), 5))},
                ('person','interacts_with','person'):{'edge_index': torch.combinations(torch.arange(5), r=2).t()}
            }))
        },
        "travel_day_paris": { # Robustness test: Location Invariance
            "time_gen": lambda: np.random.uniform(540, 1260, size=60), # 9am-9pm
            "graph_gen": lambda: create_travel_graph(location='paris')
        },
        "travel_day_bangalore": { # Robustness test: Location Invariance
            "time_gen": lambda: np.random.uniform(540, 1260, size=60), # 9am-9pm
            "graph_gen": lambda: create_travel_graph(location='bengaluru')
        }
    }

    activity_names = sorted(list(activities.keys()))
    label_to_idx = {name: i for i, name in enumerate(activity_names)}
    all_temporal, all_graph, all_labels = [], [], []

    print("Generating simulated daily data for experiments...")
    for label_name in tqdm(activity_names):
        activity = activities[label_name]
        for _ in range(NUM_DAYS_PER_ACTIVITY):
            ts = np.clip(activity["time_gen"](), 0, 1439)
            graph = finalize_graph(activity["graph_gen"]())
            all_temporal.append(sorted(ts))
            all_graph.append(graph)
            all_labels.append(label_to_idx[label_name])

    return all_temporal, all_graph, all_labels, activity_names

# --- 3. Model Definitions (Unchanged from previous response) ---
class TemporalDataset(Dataset):
    def __init__(self, daily_data, max_seq_len=T_MAX_SEQ_LEN, num_hist_bins=T_NUM_HIST_BINS):
        self.daily_data, self.max_seq_len, self.num_hist_bins = daily_data, max_seq_len, num_hist_bins
    def __len__(self): return len(self.daily_data)
    def create_hourly_histogram(self, ts):
        hist, _ = np.histogram(ts, bins=np.linspace(0, 1440, self.num_hist_bins + 1)); return hist / (np.sum(hist) + 1e-9)
    def __getitem__(self, idx):
        ts = self.daily_data[idx]; features = []
        if ts:
            prev_time = 0
            for t in ts:
                h, m = t // 60, t % 60
                features.append([sin(2*pi*h/24),cos(2*pi*h/24),sin(2*pi*m/60),cos(2*pi*m/60),(t-prev_time)/1440.0]); prev_time = t
        features.extend([[0.0] * 5 for _ in range(self.max_seq_len - len(features))])
        return torch.tensor(features[:self.max_seq_len], dtype=torch.float32), torch.tensor(self.create_hourly_histogram(ts), dtype=torch.float32)

class TemporalSpreadVGAE(nn.Module):
    def __init__(self, i, h, l, o, n=2):
        super().__init__(); self.encoder_rnn = nn.LSTM(i,h,n,batch_first=True,bidirectional=True); self.fc_mu = nn.Linear(h*2,l); self.fc_logvar = nn.Linear(h*2,l); self.decoder_fc = nn.Sequential(nn.Linear(l,h),nn.ReLU(),nn.Linear(h,o),nn.Softmax(dim=-1))
    def encode(self, x): _, (h, _) = self.encoder_rnn(x); h = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1); return self.fc_mu(h), self.fc_logvar(h)
    def reparameterize(self, mu, logvar): std=torch.exp(0.5*logvar); eps=torch.randn_like(std); return mu+eps*std
    def forward(self, x): mu, logvar = self.encode(x); z = self.reparameterize(mu, logvar); return self.decoder_fc(z), mu, logvar

class DSENVGAE(nn.Module):
    def __init__(self, n, e, l, n_layers, meta):
        super().__init__(); self.latent_dim, self.metadata = l, meta; self.lin_dict = nn.ModuleDict({nt: nn.Linear(n,e) for nt in meta[0]}); self.han_convs = nn.ModuleList([HANConv(e,e,metadata=meta,heads=4) for _ in range(n_layers)]); self.mu_linear, self.logvar_linear = nn.Linear(e,l), nn.Linear(e,l)
    def encode(self, data):
        x_dict = {nt: self.lin_dict[nt](x) for nt, x in data.x_dict.items()}; [x_dict := conv(x_dict, data.edge_index_dict) for conv in self.han_convs]
        pooled = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]; p_mean = torch.stack(pooled).mean(dim=0) if pooled else torch.zeros(G_EMBEDDING_DIM, device=DEVICE); return self.mu_linear(p_mean), self.logvar_linear(p_mean), x_dict
    def reparameterize(self, mu, logvar): std = torch.exp(0.5*logvar); eps = torch.randn_like(std); return mu+eps*std
    def decode(self, z, h_dict, edge_index_dict):
        loss, n_types = 0, 0
        for et, ei in edge_index_dict.items():
            if ei.numel() == 0: continue
            n_types+=1; st,_,dt=et; pos_src_idx,pos_dst_idx=ei[0],ei[1]; pos_src_emb,pos_dst_emb=h_dict[st][pos_src_idx],h_dict[dt][pos_dst_idx]; pos_score=(pos_src_emb*pos_dst_emb).sum(dim=-1)
            neg_dst_idx=torch.randint(0,h_dict[dt].size(0),(len(pos_dst_idx),),device=z.device); neg_dst_emb=h_dict[dt][neg_dst_idx]; neg_score=(pos_src_emb*neg_dst_emb).sum(dim=-1); loss+=-torch.log(torch.sigmoid(pos_score-neg_score)+1e-9).mean()
        return loss/(n_types+1e-9)
    def forward(self, data): return self.encode(data)
    def loss(self, mu, logvar, h_dict, orig_data, beta): z=self.reparameterize(mu,logvar); recon_loss=self.decode(z,h_dict,orig_data.edge_index_dict); kl_loss=-0.5*torch.sum(1+logvar-mu.pow(2)-logvar.exp()); return recon_loss+beta*kl_loss

# --- 4. Training and Evaluation Functions ---
def train_temporal_model(data, epochs):
    print("\n--- Training Temporal Spread VAE ---")
    dataset = TemporalDataset(data); loader = DataLoader(dataset, batch_size=32, shuffle=True)
    model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, T_NUM_HIST_BINS).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    for epoch in range(epochs):
        for features, histograms in tqdm(loader, desc=f"Temporal Epoch {epoch+1}/{epochs}", leave=False):
            features, histograms = features.to(DEVICE), histograms.to(DEVICE); optimizer.zero_grad()
            recon_hist, mu, logvar = model(features); recon_loss = F.kl_div(torch.log(recon_hist + 1e-9), histograms, reduction='batchmean'); kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()); loss = recon_loss + BETA_KL * kl_loss / features.size(0); loss.backward(); optimizer.step()
    return model

def train_graph_model(data, epochs):
    print("--- Training Social/Activity (Graph) VAE ---")
    metadata = (NODE_TYPES, EDGE_TYPES)
    model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, metadata).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    for epoch in range(epochs):
        for graph_data in tqdm(data, desc=f"Graph Epoch {epoch+1}/{epochs}", leave=False):
            graph_data = graph_data.to(DEVICE); optimizer.zero_grad(); mu, logvar, h_dict = model(graph_data); loss = model.loss(mu, logvar, h_dict, graph_data, BETA_KL)
            if not torch.isnan(loss): loss.backward(); optimizer.step()
    return model

@torch.no_grad()
def get_all_embeddings(temporal_model, graph_model, temporal_data, graph_data):
    print("--- Extracting and Aggregating Embeddings ---")
    temporal_model.eval(); graph_model.eval()
    temporal_dataset = TemporalDataset(temporal_data)
    t_embs, g_embs = [], []
    for i in range(len(temporal_dataset)):
        features, _ = temporal_dataset[i]
        mu, _ = temporal_model.encode(features.unsqueeze(0).to(DEVICE)); t_embs.append(mu.cpu().numpy().flatten())
        g_data = graph_data[i].to(DEVICE); mu, _, _ = graph_model.encode(g_data); g_embs.append(mu.cpu().numpy().flatten())
    t_embs, g_embs = np.array(t_embs), np.array(g_embs)
    agg_embs = np.concatenate([t_embs, g_embs], axis=1)
    return t_embs, g_embs, agg_embs

def calculate_and_print_distances(embeddings, labels, title):
    unique_labels = np.unique(labels)
    intra_class_distances, inter_class_distances = [], []
    # Use cdist for efficient calculation of all pairwise distances
    dist_matrix = cdist(embeddings, embeddings, 'euclidean')
    for i in range(len(labels)):
        for j in range(i + 1, len(labels)):
            if labels[i] == labels[j]:
                intra_class_distances.append(dist_matrix[i, j])
            else:
                inter_class_distances.append(dist_matrix[i, j])
    intra_mean = np.mean(intra_class_distances) if intra_class_distances else 0
    inter_mean = np.mean(inter_class_distances) if inter_class_distances else 0
    print(f"| {title:<19} | {intra_mean:<25.3f} | {inter_mean:<25.3f} |")
    return intra_mean, inter_mean

def plot_tsne(embeddings, labels, class_names):
    print("--- Generating t-SNE Plot ---")
    tsne = TSNE(n_components=2, perplexity=30, n_iter=1200, random_state=42, init='pca')
    tsne_results = tsne.fit_transform(embeddings)

    plt.figure(figsize=(16, 12))
    num_classes = len(class_names)
    # Use a color map that provides distinct colors
    colors = plt.cm.get_cmap('tab10', num_classes)

    for i, name in enumerate(class_names):
        idx = np.where(np.array(labels) == i)
        plt.scatter(tsne_results[idx, 0], tsne_results[idx, 1], color=colors(i), label=name, alpha=0.8, s=50)

    plt.title('t-SNE of Aggregate Day Dynamics Embeddings (with Robustness Tests)', fontsize=20)
    plt.xlabel('t-SNE Dimension 1', fontsize=14)
    plt.ylabel('t-SNE Dimension 2', fontsize=14)
    plt.legend(title="Activity Types", fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.5)

    # Add annotations to explain the robustness results
    plt.annotate('Temporal Shift\n(Same activity, diff. time)', xy=(-40, 50), xytext=(-65, 60),
                 arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=8),
                 fontsize=12, bbox=dict(boxstyle="round,pad=0.3", fc="yellow", ec="black", lw=1, alpha=0.8))
    plt.annotate('Location Invariance\n(Same dynamics, diff. scenes)', xy=(45, -5), xytext=(55, -30),
                 arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=8),
                 fontsize=12, bbox=dict(boxstyle="round,pad=0.3", fc="cyan", ec="black", lw=1, alpha=0.8))

    plt.show()

# --- 5. Main Execution ---

# 1. Generate Data
temporal_data, graph_data, labels, activity_names = generate_daily_data()

# 2. Train Models
temporal_model = train_temporal_model(temporal_data, EPOCHS_TEMPORAL)
graph_model = train_graph_model(graph_data, EPOCHS_GRAPH)

# 3. Get All Embeddings
t_embs, g_embs, agg_embs = get_all_embeddings(temporal_model, graph_model, temporal_data, graph_data)

# 4. Perform Inter/Intra-Class Distance Analysis
print("\n--- Inter/Intra-Class Distance Analysis ---")
print("-" * 75)
print(f"| {'Embedding Type':<19} | {'Avg. Intra-Class Distance':<25} | {'Avg. Inter-Class Distance':<25} |")
print("-" * 75)
calculate_and_print_distances(t_embs, labels, "Temporal Only")
calculate_and_print_distances(g_embs, labels, "Graph Only")
calculate_and_print_distances(agg_embs, labels, "Aggregate (Final)")
print("-" * 75)

# 5. Plot Final t-SNE for Robustness Analysis
plot_tsne(agg_embs, labels, activity_names)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
from math import sin, cos, pi
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import random
from tqdm import tqdm
from scipy.spatial.distance import cdist
import matplotlib.colors as mcolors

# Attempt to import PyTorch Geometric
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv
except ImportError:
    print("PyTorch Geometric not found. Please install it via: pip install torch_geometric")
    exit()

# --- 1. Configuration & Constants ---
# General Config
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_DAYS_PER_ACTIVITY = 40 # 40 days for each activity variant
EPOCHS_TEMPORAL = 5
EPOCHS_GRAPH = 5
BETA_KL = 0.5

# Model Configs
T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM = 5, 64, 16
T_MAX_SEQ_LEN, T_NUM_HIST_BINS = 150, 24
G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS = 64, 32, 2
NODE_FEATURE_DIM = 32

# --- 2. Enhanced Data Simulation for Robustness ---

NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log')
]

# Feature pools for nodes, including location-specific scenes
PERSON_FEATURES = {f"person_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(20)}
SCENE_FEATURES = {
    **{f"generic_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(5)},
    **{f"paris_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(3)},
    **{f"bengaluru_scene_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(3)},
}
ACTIVITY_LOG_FEATURES = {f"log_{i}": torch.randn(NODE_FEATURE_DIM) for i in range(5)}

# --- Graph Generation Helpers ---
def create_walk_graph(is_evening=False):
    data = HeteroData()
    persons = ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 1)
    scenes = random.sample([s for s in SCENE_FEATURES if 'generic' in s], 2)
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1], [0, 1]], dtype=torch.long)
    return data

def create_work_graph(is_solo=False):
    data = HeteroData()
    persons = ['person_0'] if is_solo else ['person_0'] + random.sample([p for p in PERSON_FEATURES if p != 'person_0'], 2)
    scenes = ['generic_scene_0', 'generic_scene_1'] # Home, Office
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    if not is_solo:
        data['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0, 0], [1, 2]], dtype=torch.long)
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[p_idx, 1] for p_idx in range(len(persons))], dtype=torch.long).t()
    return data

def create_travel_graph(location='paris'):
    data = HeteroData()
    persons = ['person_0']
    scene_keys = [s for s in SCENE_FEATURES if location in s]
    scenes = random.sample(scene_keys, 2)
    logs = random.sample(list(ACTIVITY_LOG_FEATURES.keys()), 3)
    data['person'].x = torch.stack([PERSON_FEATURES[p] for p in persons])
    data['scene'].x = torch.stack([SCENE_FEATURES[s] for s in scenes])
    data['activity_log'].x = torch.stack([ACTIVITY_LOG_FEATURES[l] for l in logs])
    data['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 0], [0, 1]], dtype=torch.long)
    data['person', 'performs', 'activity_log'].edge_index = torch.tensor([[0,0,0],[0,1,2]], dtype=torch.long)
    return data

def finalize_graph(data):
    for n_type in NODE_TYPES:
        if n_type not in data.node_types:
            data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)
    for e_type in EDGE_TYPES:
        if e_type not in data.edge_types:
            data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)
    return data

def generate_daily_data():
    """Generates temporal and graph data for core activities and robustness tests."""
    activities = {
        "morning_walk": {"time_gen": lambda: np.random.normal(loc=420, scale=30, size=30), "graph_gen": lambda: create_walk_graph()},
        "evening_walk": {"time_gen": lambda: np.random.normal(loc=1080, scale=30, size=30), "graph_gen": lambda: create_walk_graph()},
        "work_day": {"time_gen": lambda: np.concatenate([np.random.normal(loc=570, scale=60, size=40), np.random.normal(loc=900, scale=60, size=40)]), "graph_gen": lambda: create_work_graph(is_solo=False)},
        "work_day_solo": {"time_gen": lambda: np.concatenate([np.random.normal(loc=570, scale=60, size=40), np.random.normal(loc=900, scale=60, size=40)]), "graph_gen": lambda: create_work_graph(is_solo=True)},
        "family_event": {"time_gen": lambda: np.random.normal(loc=1140, scale=45, size=80), "graph_gen": lambda: finalize_graph(HeteroData({'person':{'x': torch.stack(random.sample(list(PERSON_FEATURES.values()), 5))},('person','interacts_with','person'):{'edge_index': torch.combinations(torch.arange(5), r=2).t()}}))},
        "travel_day_paris": {"time_gen": lambda: np.random.uniform(540, 1260, size=60), "graph_gen": lambda: create_travel_graph(location='paris')},
        "travel_day_bangalore": {"time_gen": lambda: np.random.uniform(540, 1260, size=60), "graph_gen": lambda: create_travel_graph(location='bengaluru')}
    }
    activity_names = sorted(list(activities.keys())); label_to_idx = {name: i for i, name in enumerate(activity_names)}; all_temporal, all_graph, all_labels = [], [], []
    print("Generating simulated daily data for experiments...")
    for label_name in tqdm(activity_names, desc="Generating Data"):
        activity = activities[label_name]
        for _ in range(NUM_DAYS_PER_ACTIVITY):
            ts = np.clip(activity["time_gen"](), 0, 1439); graph = finalize_graph(activity["graph_gen"]()); all_temporal.append(sorted(ts)); all_graph.append(graph); all_labels.append(label_to_idx[label_name])
    return all_temporal, all_graph, all_labels, activity_names

# --- 3. Model Definitions ---
class TemporalDataset(Dataset):
    def __init__(self, daily_data, max_seq_len=T_MAX_SEQ_LEN, num_hist_bins=T_NUM_HIST_BINS): self.daily_data, self.max_seq_len, self.num_hist_bins = daily_data, max_seq_len, num_hist_bins
    def __len__(self): return len(self.daily_data)
    def create_hourly_histogram(self, ts): hist, _ = np.histogram(ts, bins=np.linspace(0, 1440, self.num_hist_bins + 1)); return hist / (np.sum(hist) + 1e-9)
    def __getitem__(self, idx):
        ts = self.daily_data[idx]; features = []; prev_time = 0
        if ts:
            for t in ts: h, m = t // 60, t % 60; features.append([sin(2*pi*h/24),cos(2*pi*h/24),sin(2*pi*m/60),cos(2*pi*m/60),(t-prev_time)/1440.0]); prev_time = t
        features.extend([[0.0] * 5 for _ in range(self.max_seq_len - len(features))])
        return torch.tensor(features[:self.max_seq_len], dtype=torch.float32), torch.tensor(self.create_hourly_histogram(ts), dtype=torch.float32)

class TemporalSpreadVGAE(nn.Module):
    def __init__(self, i, h, l, o, n=2): super().__init__(); self.encoder_rnn = nn.LSTM(i,h,n,batch_first=True,bidirectional=True); self.fc_mu = nn.Linear(h*2,l); self.fc_logvar = nn.Linear(h*2,l); self.decoder_fc = nn.Sequential(nn.Linear(l,h),nn.ReLU(),nn.Linear(h,o),nn.Softmax(dim=-1))
    def encode(self, x): _, (h, _) = self.encoder_rnn(x); h = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1); return self.fc_mu(h), self.fc_logvar(h)
    def reparameterize(self, mu, logvar): std=torch.exp(0.5*logvar); eps=torch.randn_like(std); return mu+eps*std
    def forward(self, x): mu, logvar = self.encode(x); z = self.reparameterize(mu, logvar); return self.decoder_fc(z), mu, logvar

class DSENVGAE(nn.Module):
    def __init__(self, n, e, l, n_layers, meta): super().__init__(); self.latent_dim, self.metadata = l, meta; self.lin_dict = nn.ModuleDict({nt: nn.Linear(n,e) for nt in meta[0]}); self.han_convs = nn.ModuleList([HANConv(e,e,metadata=meta,heads=4) for _ in range(n_layers)]); self.mu_linear, self.logvar_linear = nn.Linear(e,l), nn.Linear(e,l)
    def encode(self, data):
        x_dict = {nt: self.lin_dict[nt](x) for nt, x in data.x_dict.items()}; [x_dict := conv(x_dict, data.edge_index_dict) for conv in self.han_convs]; pooled = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]; p_mean = torch.stack(pooled).mean(dim=0) if pooled else torch.zeros(G_EMBEDDING_DIM, device=DEVICE); return self.mu_linear(p_mean), self.logvar_linear(p_mean), x_dict
    def reparameterize(self, mu, logvar): std = torch.exp(0.5*logvar); eps = torch.randn_like(std); return mu+eps*std
    def decode(self, z, h_dict, edge_index_dict):
        loss, n_types = 0, 0
        for et, ei in edge_index_dict.items():
            if ei.numel() == 0: continue
            n_types+=1; st,_,dt=et; pos_src_idx,pos_dst_idx=ei[0],ei[1]; pos_src_emb,pos_dst_emb=h_dict[st][pos_src_idx],h_dict[dt][pos_dst_idx]; pos_score=(pos_src_emb*pos_dst_emb).sum(dim=-1); neg_dst_idx=torch.randint(0,h_dict[dt].size(0),(len(pos_dst_idx),),device=z.device); neg_dst_emb=h_dict[dt][neg_dst_idx]; neg_score=(pos_src_emb*neg_dst_emb).sum(dim=-1); loss+=-torch.log(torch.sigmoid(pos_score-neg_score)+1e-9).mean()
        return loss/(n_types+1e-9)
    def forward(self, data): return self.encode(data)
    def loss(self, mu, logvar, h_dict, orig_data, beta): z=self.reparameterize(mu,logvar); recon_loss=self.decode(z,h_dict,orig_data.edge_index_dict); kl_loss=-0.5*torch.sum(1+logvar-mu.pow(2)-logvar.exp()); return recon_loss+beta*kl_loss

# --- 4. Training and Evaluation Functions ---
def train_temporal_model(data, epochs):
    print("\n--- Training Temporal Spread VAE ---")
    dataset = TemporalDataset(data); loader = DataLoader(dataset, batch_size=32, shuffle=True)
    model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, T_NUM_HIST_BINS).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    for epoch in range(epochs):
        for features, histograms in tqdm(loader, desc=f"Temporal Epoch {epoch+1}/{epochs}", leave=False):
            features, histograms = features.to(DEVICE), histograms.to(DEVICE); optimizer.zero_grad(); recon_hist, mu, logvar = model(features); recon_loss = F.kl_div(torch.log(recon_hist + 1e-9), histograms, reduction='batchmean'); kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()); loss = recon_loss + BETA_KL * kl_loss / features.size(0); loss.backward(); optimizer.step()
    return model

def train_graph_model(data, epochs):
    print("--- Training Social/Activity (Graph) VAE ---")
    metadata = (NODE_TYPES, EDGE_TYPES)
    model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, metadata).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    for epoch in range(epochs):
        for graph_data in tqdm(data, desc=f"Graph Epoch {epoch+1}/{epochs}", leave=False):
            graph_data = graph_data.to(DEVICE); optimizer.zero_grad(); mu, logvar, h_dict = model(graph_data); loss = model.loss(mu, logvar, h_dict, graph_data, BETA_KL)
            if not torch.isnan(loss): loss.backward(); optimizer.step()
    return model

@torch.no_grad()
def get_all_embeddings(temporal_model, graph_model, temporal_data, graph_data):
    desc = "Extracting Embeddings"
    if len(temporal_data) < sum(NUM_DAYS_PER_ACTIVITY for _ in range(7)): # A simple check to see if it's a smaller (e.g., test or mixed) set
        desc = "Extracting Embeddings (Subset)"
    print(f"--- {desc} ---")
    temporal_model.eval(); graph_model.eval(); temporal_dataset = TemporalDataset(temporal_data); t_embs, g_embs = [], []
    for i in tqdm(range(len(temporal_dataset)), desc=desc, leave=False):
        features, _ = temporal_dataset[i]; mu, _ = temporal_model.encode(features.unsqueeze(0).to(DEVICE)); t_embs.append(mu.cpu().numpy().flatten())
        g_data = graph_data[i].to(DEVICE); mu, _, _ = graph_model.encode(g_data); g_embs.append(mu.cpu().numpy().flatten())
    t_embs, g_embs = np.array(t_embs), np.array(g_embs)
    agg_embs = np.concatenate([t_embs, g_embs], axis=1)
    return t_embs, g_embs, agg_embs

def calculate_and_print_distances(embeddings, labels, title):
    dist_matrix = cdist(embeddings, embeddings, 'euclidean'); intra_class_distances, inter_class_distances = [], []
    for i in range(len(labels)):
        for j in range(i + 1, len(labels)):
            (intra_class_distances if labels[i] == labels[j] else inter_class_distances).append(dist_matrix[i, j])
    intra_mean = np.mean(intra_class_distances) if intra_class_distances else 0; inter_mean = np.mean(inter_class_distances) if inter_class_distances else 0
    print(f"| {title:<19} | {intra_mean:<25.3f} | {inter_mean:<25.3f} |")
    return intra_mean, inter_mean

def plot_tsne(embeddings, labels, class_names, title):
    print(f"--- Generating t-SNE Plot: {title} ---")
    tsne = TSNE(n_components=2, perplexity=min(30, len(embeddings)-1), n_iter=1200, random_state=42, init='pca'); tsne_results = tsne.fit_transform(embeddings)
    plt.figure(figsize=(16, 12)); num_classes = len(class_names); colors = plt.cm.get_cmap('tab10', num_classes)
    for i, name in enumerate(class_names):
        idx = np.where(np.array(labels) == i)
        plt.scatter(tsne_results[idx, 0], tsne_results[idx, 1], color=colors(i), label=name, alpha=0.8, s=50)
    plt.title(title, fontsize=20); plt.xlabel('t-SNE Dimension 1', fontsize=14); plt.ylabel('t-SNE Dimension 2', fontsize=14); plt.legend(title="Activity Types", fontsize=12); plt.grid(True, linestyle='--', alpha=0.5); plt.show()

def plot_tsne_with_mixed(base_embs, base_labels, base_names, mixed_embs, mixed_names, title):
    print(f"--- Generating t-SNE Plot: {title} ---")
    combined_embs = np.vstack([base_embs, mixed_embs]); tsne = TSNE(n_components=2, perplexity=30, n_iter=1200, random_state=42, init='pca'); tsne_results = tsne.fit_transform(combined_embs)
    base_tsne, mixed_tsne = tsne_results[:len(base_embs)], tsne_results[len(base_embs):]; plt.figure(figsize=(18, 14)); num_classes = len(base_names); colors = plt.cm.get_cmap('tab10', num_classes)
    for i, name in enumerate(base_names):
        idx = np.where(np.array(base_labels) == i)
        plt.scatter(base_tsne[idx, 0], base_tsne[idx, 1], color=colors(i), label=name, alpha=0.7, s=60)
    for i, name in enumerate(mixed_names):
        plt.scatter(mixed_tsne[i, 0], mixed_tsne[i, 1], color='black', marker='X', s=250, label=name, edgecolors='white', linewidth=1.5, zorder=5)
    plt.title(title, fontsize=22); plt.xlabel('t-SNE Dimension 1', fontsize=16); plt.ylabel('t-SNE Dimension 2', fontsize=16); plt.legend(title="Activity Types", fontsize=14); plt.grid(True, linestyle='--', alpha=0.5); plt.show()

# --- 5. New Experimental Workflow ---

def run_baseline_analysis():
    """EXPERIMENT 1: Baseline analysis + Plot individual & aggregate embeddings."""
    print("\n\n" + "="*80 + "\n🚀 EXPERIMENT 1: BASELINE ANALYSIS & INDIVIDUAL EMBEDDING PLOTS\n" + "="*80)
    all_temporal, all_graph, all_labels, activity_names = generate_daily_data()
    temporal_model = train_temporal_model(all_temporal, EPOCHS_TEMPORAL)
    graph_model = train_graph_model(all_graph, EPOCHS_GRAPH)
    t_embs, g_embs, agg_embs = get_all_embeddings(temporal_model, graph_model, all_temporal, all_graph)

    print("\n--- Inter/Intra-Class Distance Analysis ---")
    print("-" * 75 + f"\n| {'Embedding Type':<19} | {'Avg. Intra-Class Distance':<25} | {'Avg. Inter-Class Distance':<25} |\n" + "-" * 75)
    calculate_and_print_distances(t_embs, all_labels, "Temporal Only"); calculate_and_print_distances(g_embs, all_labels, "Graph Only"); calculate_and_print_distances(agg_embs, all_labels, "Aggregate (Final)")
    print("-" * 75)

    # Request 1: Plot t-SNE for each embedding type
    plot_tsne(t_embs, all_labels, activity_names, "t-SNE of Temporal Embeddings Only")
    plot_tsne(g_embs, all_labels, activity_names, "t-SNE of Graph Embeddings Only")
    plot_tsne(agg_embs, all_labels, activity_names, "t-SNE of Aggregate Embeddings (Baseline)")

    return temporal_model, graph_model, all_temporal, all_graph, all_labels, activity_names, agg_embs

def run_inductive_experiment():
    """EXPERIMENT 2: Demonstrate inductive capabilities."""
    print("\n\n" + "="*80 + "\n🧠 EXPERIMENT 2: INDUCTIVE CAPABILITY DEMONSTRATION\n" + "="*80)
    print("Goal: Train on a subset of data and test on unseen data to show the model can generalize.\n")
    all_temporal, all_graph, all_labels, activity_names = generate_daily_data()
    train_temporal, test_temporal, train_graph, test_graph, train_labels, test_labels = [], [], [], [], [], []
    n_train_per_activity = 30

    for i in range(len(activity_names)):
        start_idx = i * NUM_DAYS_PER_ACTIVITY; train_end = start_idx + n_train_per_activity; test_end = start_idx + NUM_DAYS_PER_ACTIVITY
        train_temporal.extend(all_temporal[start_idx:train_end]); train_graph.extend(all_graph[start_idx:train_end]); train_labels.extend(all_labels[start_idx:train_end])
        test_temporal.extend(all_temporal[train_end:test_end]); test_graph.extend(all_graph[train_end:test_end]); test_labels.extend(all_labels[train_end:test_end])

    print(f"Data split: {len(train_labels)} training samples, {len(test_labels)} unseen test samples.")

    temporal_model = train_temporal_model(train_temporal, EPOCHS_TEMPORAL)
    graph_model = train_graph_model(train_graph, EPOCHS_GRAPH)

    print("\n--- Generating embeddings for the UNSEEN test data ---")
    _, _, agg_embs_test = get_all_embeddings(temporal_model, graph_model, test_temporal, test_graph)

    plot_tsne(agg_embs_test, test_labels, activity_names, "t-SNE of Unseen Data (Inductive Test)")
    print("\n✅ Analysis: If clusters are well-formed, it shows the model learned general patterns (inductive) rather than just memorizing (transductive).")

def run_mixed_activity_experiment(t_model, g_model, base_temp, base_graph, base_labels, base_agg_embs, act_names):
    """EXPERIMENT 3: Analyze embeddings of mixed activities."""
    print("\n\n" + "="*80 + "\n🎭 EXPERIMENT 3: MIXED ACTIVITY EMBEDDING ANALYSIS\n" + "="*80)
    print("Goal: Show that embeddings for artificially mixed activities fall between original clusters.\n")

    mixed_temporal, mixed_graph, mixed_labels_desc = [], [], []
    try:
        walk_idx = base_labels.index(act_names.index('morning_walk'))
        family_idx = base_labels.index(act_names.index('family_event'))
        work_idx = base_labels.index(act_names.index('work_day'))
        travel_idx = base_labels.index(act_names.index('travel_day_paris'))

        # Mix 1: Temporal from 'walk', Graph from 'family'
        mixed_temporal.append(base_temp[walk_idx]); mixed_graph.append(base_graph[family_idx]); mixed_labels_desc.append("Walk(T) + Family(G)")
        # Mix 2: Temporal from 'work', Graph from 'travel'
        mixed_temporal.append(base_temp[work_idx]); mixed_graph.append(base_graph[travel_idx]); mixed_labels_desc.append("Work(T) + Travel(G)")

        print(f"Created {len(mixed_labels_desc)} mixed-activity data points.")
    except ValueError as e:
        print(f"Could not create mixed data, an activity type might be missing: {e}"); return

    _, _, mixed_agg_embs = get_all_embeddings(t_model, g_model, mixed_temporal, mixed_graph)

    plot_tsne_with_mixed(base_agg_embs, base_labels, act_names, mixed_agg_embs, mixed_labels_desc, "t-SNE with Mixed Activities Overlaid (Marked with 'X')")
    print("\n✅ Analysis: The 'X' markers should appear between their constituent clusters, showing the model's confusion and motivating the need for methods to disentangle mixed signals.")


if __name__ == "__main__":
    # Request 1: Run baseline, plotting individual and aggregate embeddings
    t_model, g_model, base_temp, base_graph, base_labels, act_names, base_agg_embs = run_baseline_analysis()

    # Request 2: Run inductive learning experiment
    run_inductive_experiment()

    # Request 3: Run mixed-activity experiment using models from the baseline
    run_mixed_activity_experiment(t_model, g_model, base_temp, base_graph, base_labels, base_agg_embs, act_names)





"""Node and Graph embeddings"""

import torch
import torch.nn as nn
import numpy as np
from math import sin, cos, pi
import random
import os

# Attempt to import PyTorch Geometric
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv
except ImportError:
    print("PyTorch Geometric not found. Please install it via: pip install torch_geometric")
    # In a real application, you'd want to handle this more gracefully
    # or ensure the dependency is met.
    exit()

# --- 1. Configuration Constants ---
# These should match the configuration used during model training.
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Model Configs
T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM = 5, 64, 16
T_MAX_SEQ_LEN = 150
G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS = 64, 32, 2
NODE_FEATURE_DIM = 32

# Graph Structure Metadata
NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log')
]

# --- 2. Model Architecture Definitions ---
# These classes define the neural network architectures. They must be
# identical to the ones used for training the models you are loading.

class TemporalSpreadVGAE(nn.Module):
    """
    Temporal Variational Graph Autoencoder for time-series data.
    Encodes a sequence of events into a latent vector.
    """
    def __init__(self, input_dim, hidden_dim, latent_dim, output_dim, num_layers=2):
        super().__init__()
        self.encoder_rnn = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)
        self.fc_mu = nn.Linear(hidden_dim * 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim * 2, latent_dim)
        # Decoder is not needed for embedding generation, but included for completeness
        self.decoder_fc = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
            nn.Softmax(dim=-1)
        )

    def encode(self, x):
        _, (h, _) = self.encoder_rnn(x)
        # Concatenate the final hidden states from both directions
        h_concat = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1)
        mu = self.fc_mu(h_concat)
        logvar = self.fc_logvar(h_concat)
        return mu, logvar

    def forward(self, x):
        # For inference, we only need the encoding part.
        mu, _ = self.encode(x)
        return mu

class DSENVGAE(nn.Module):
    """
    Dynamic Social Entity Network VGAE for heterogeneous graphs.
    Encodes a graph's structure and node features into a latent vector
    and produces embeddings for each node.
    """
    def __init__(self, node_feat_dim, embed_dim, latent_dim, num_han_layers, metadata):
        super().__init__()
        self.latent_dim = latent_dim
        self.metadata = metadata

        # Linear projection for each node type
        self.lin_dict = nn.ModuleDict({
            nt: nn.Linear(node_feat_dim, embed_dim) for nt in metadata[0]
        })

        # Heterogeneous Graph Attention Layers
        self.han_convs = nn.ModuleList([
            HANConv(embed_dim, embed_dim, metadata=metadata, heads=4) for _ in range(num_han_layers)
        ])

        # Output layers for graph-level embedding
        self.mu_linear = nn.Linear(embed_dim, latent_dim)
        self.logvar_linear = nn.Linear(embed_dim, latent_dim)

    def encode(self, data):
        # Project node features into a common embedding space
        x_dict = {nt: self.lin_dict[nt](x) for nt, x in data.x_dict.items()}

        # Process through HAN layers
        for conv in self.han_convs:
            x_dict = conv(x_dict, data.edge_index_dict)

        # Pool node embeddings to get a graph-level representation
        # We only pool from node types that actually have nodes in the graph
        pooled_embs = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]

        if pooled_embs:
            graph_level_emb = torch.stack(pooled_embs).mean(dim=0)
        else:
            # Handle empty graphs
            graph_level_emb = torch.zeros(self.mu_linear.in_features, device=next(self.parameters()).device)

        mu = self.mu_linear(graph_level_emb)
        logvar = self.logvar_linear(graph_level_emb)

        # Return graph-level latent variables and node-level embeddings
        return mu, logvar, x_dict

    def forward(self, data):
        # For inference, we only need the encoding part.
        mu, _, node_embeddings = self.encode(data)
        return mu, node_embeddings


# --- 3. Reusable Embedding Generator Class ---

class EmbeddingGenerator:
    """
    A class to load pre-trained models and generate temporal, graph,
    and node embeddings for new, unseen daily data.
    """
    def __init__(self, temporal_model_path, graph_model_path, device=DEVICE):
        """
        Initializes the generator by loading pre-trained model weights.

        Args:
            temporal_model_path (str): Path to the .pth file for the temporal model.
            graph_model_path (str): Path to the .pth file for the graph model.
            device (torch.device): The device to run the models on (e.g., 'cpu' or 'cuda').
        """
        self.device = device
        print(f"Initializing EmbeddingGenerator on device: {self.device}")

        # Initialize model architectures
        # Note: The output_dim for the temporal decoder isn't used for inference,
        # so we can set it to a placeholder value like 24.
        self.temporal_model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24).to(self.device)
        self.graph_model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES)).to(self.device)

        # Load pre-trained weights
        self.temporal_model.load_state_dict(torch.load(temporal_model_path, map_location=self.device))
        self.graph_model.load_state_dict(torch.load(graph_model_path, map_location=self.device))

        # Set models to evaluation mode
        self.temporal_model.eval()
        self.graph_model.eval()

        print("Models loaded and set to evaluation mode successfully.")

    def _preprocess_temporal_data(self, timestamps):
        """
        Converts a list of timestamps (in minutes) into a feature tensor.
        """
        features = []
        prev_time = 0
        # Sort timestamps to ensure correct time difference calculation
        sorted_ts = sorted(timestamps)

        for t in sorted_ts:
            h, m = t // 60, t % 60
            # Features: sin/cos of hour, sin/cos of minute, normalized time delta
            features.append([
                sin(2 * pi * h / 24), cos(2 * pi * h / 24),
                sin(2 * pi * m / 60), cos(2 * pi * m / 60),
                (t - prev_time) / 1440.0
            ])
            prev_time = t

        # Pad the sequence to the maximum length
        padding_needed = T_MAX_SEQ_LEN - len(features)
        if padding_needed > 0:
            features.extend([[0.0] * T_INPUT_DIM for _ in range(padding_needed)])

        # Truncate if longer than max length
        features = features[:T_MAX_SEQ_LEN]

        return torch.tensor(features, dtype=torch.float32).unsqueeze(0) # Add batch dimension

    def _finalize_graph(self, graph_data):
        """
        Ensures a HeteroData object has all required node and edge types defined,
        even if they are empty, to prevent errors in the graph model.
        """
        for n_type in NODE_TYPES:
            if n_type not in graph_data.node_types:
                # Add an empty tensor with the correct feature dimension
                graph_data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)

        for e_type in EDGE_TYPES:
            if e_type not in graph_data.edge_types:
                # Add an empty edge index tensor
                graph_data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)
        return graph_data

    @torch.no_grad()
    def get_embeddings(self, timestamps, graph_data):
        """
        Computes all embeddings for a given set of timestamps and a graph.

        Args:
            timestamps (list[int]): A list of event timestamps in minutes from midnight (e.g., [540, 555, 720]).
            graph_data (torch_geometric.data.HeteroData): The graph for the day.

        Returns:
            dict: A dictionary containing the following embeddings:
                  - 'temporal_embedding': (np.array)
                  - 'graph_embedding': (np.array)
                  - 'aggregate_embedding': (np.array)
                  - 'node_embeddings': (dict of np.array)
        """
        # 1. Preprocess and get temporal embedding
        temporal_input = self._preprocess_temporal_data(timestamps).to(self.device)
        temporal_mu, _ = self.temporal_model.encode(temporal_input)

        # 2. Preprocess and get graph and node embeddings
        finalized_graph = self._finalize_graph(graph_data).to(self.device)
        graph_mu, _, node_embs_dict = self.graph_model.encode(finalized_graph)

        # FIX: The temporal model outputs a 2D tensor [1, latent_dim] while the
        # graph model outputs a 1D tensor [latent_dim]. We add a batch dimension
        # to the graph embedding to make them compatible for concatenation.
        if graph_mu.dim() == 1:
            graph_mu = graph_mu.unsqueeze(0)

        # 3. Combine graph and temporal embeddings
        aggregate_emb = torch.cat([temporal_mu, graph_mu], dim=1)

        # 4. Convert all tensors to numpy arrays for easy use
        results = {
            "temporal_embedding": temporal_mu.cpu().numpy().flatten(),
            "graph_embedding": graph_mu.cpu().numpy().flatten(),
            "aggregate_embedding": aggregate_emb.cpu().numpy().flatten(),
            "node_embeddings": {nt: emb.cpu().numpy() for nt, emb in node_embs_dict.items()}
        }

        return results


# --- 4. Demonstration of Usage ---

def create_dummy_trained_models():
    """
    Creates and saves dummy model weights. In a real scenario, you would
    use your actual, trained model files.
    """
    print("\n--- Creating dummy pre-trained models for demonstration ---")
    # Create instances of the models
    temp_model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24)
    graph_model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES))

    # Save their initial (random) weights
    os.makedirs("dummy_models", exist_ok=True)
    torch.save(temp_model.state_dict(), "dummy_models/temporal_model.pth")
    torch.save(graph_model.state_dict(), "dummy_models/graph_model.pth")
    print("Dummy models saved to 'dummy_models/' directory.")


if __name__ == '__main__':
    # Step 1: Create dummy model weights for this example.
    # You would skip this step if you already have trained models.
    create_dummy_trained_models()

    # Step 2: Instantiate the generator with the paths to the model weights.
    try:
        embedding_generator = EmbeddingGenerator(
            temporal_model_path="dummy_models/temporal_model.pth",
            graph_model_path="dummy_models/graph_model.pth"
        )
    except FileNotFoundError:
        print("\nError: Model files not found. Please ensure the paths are correct.")
        exit()

    # Step 3: Create new, unseen data for which to generate embeddings.
    # This simulates a new "day" of data you want to analyze.
    print("\n--- Simulating a new, unseen day's data ---")

    # Sample timestamps for a "work day"
    new_day_timestamps = [t for t in np.random.normal(loc=570, scale=60, size=40)] # Morning work
    new_day_timestamps.extend(np.random.normal(loc=900, scale=60, size=40)) # Afternoon work
    new_day_timestamps = [int(t) for t in np.clip(new_day_timestamps, 0, 1439)]

    # Sample graph for a "work day" with two people in an office
    new_day_graph = HeteroData()
    new_day_graph['person'].x = torch.randn(2, NODE_FEATURE_DIM) # Two people
    new_day_graph['scene'].x = torch.randn(1, NODE_FEATURE_DIM)  # One scene (office)
    # Both people appear in the scene
    new_day_graph['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1], [0, 0]], dtype=torch.long)
    # The two people interact
    new_day_graph['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0], [1]], dtype=torch.long)

    print(f"Generated a sample day with {len(new_day_timestamps)} events and a graph with {new_day_graph.num_nodes} nodes.")

    # Step 4: Use the generator to get the embeddings.
    print("\n--- Computing embeddings for the new data ---")
    embeddings = embedding_generator.get_embeddings(new_day_timestamps, new_day_graph)

    # Step 5: Print the results to inspect them.
    print("\n--- RESULTS ---")
    print(f"Temporal Embedding Shape: {embeddings['temporal_embedding'].shape}")
    print(f"Graph Embedding Shape:    {embeddings['graph_embedding'].shape}")
    print(f"Aggregate Embedding Shape:  {embeddings['aggregate_embedding'].shape}")
    print("\nNode Embeddings:")
    for node_type, node_embs in embeddings['node_embeddings'].items():
        print(f"  - Type '{node_type}': {node_embs.shape[0]} nodes, Embedding Shape: {node_embs.shape}")

