# -*- coding: utf-8 -*-
"""simulate_TPP_gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oane-EbCjcXzR40lgr9xo2wmkLGubp0j
"""

import random
from datetime import datetime, timedelta
import uuid
import json

# --- Configuration Parameters ---
N_USERS = 20  # Number of users to simulate
SIM_DAYS = 365  # Total simulation period in days
START_DATE = datetime(2024, 1, 1) # Start date for the simulation

# Baseline activity rates (events per day)
BASE_APP_USAGE_PER_DAY = 50
BASE_CALL_LOG_PER_DAY = 10
BASE_CALENDAR_PER_DAY = 2
BASE_CONTACT_PER_DAY = 0.1 # Less frequent
BASE_GALLERY_PER_DAY = 15

# Travel phase activity multipliers
TRAVEL_APP_MULTIPLIER = 3
TRAVEL_CALL_MULTIPLIER = 1.5
TRAVEL_GALLERY_MULTIPLIER = 5

# Interest change phase activity multipliers
INTEREST_APP_MULTIPLIER = 4
INTEREST_GALLERY_MULTIPLIER = 2
INTEREST_CALL_MULTIPLIER = 1.2

# Phase durations (in days)
TRAVEL_TRIGGER_DURATION = 1
TRAVEL_GROWING_DURATION = random.randint(3, 7) # Actual travel duration
TRAVEL_DECAY_DURATION = 2 # Post-travel settling

INTEREST_TRIGGER_DURATION = 1
INTEREST_GROWING_DURATION = random.randint(5, 10) # Initial intense interest
INTEREST_STABLE_DURATION = random.randint(30, 90) # How long the interest remains high before blending into baseline

# Probability distribution for modalities during baseline
MODALITY_PROBS = {
    'app_usage': 0.40,
    'call_log': 0.20,
    'calendar_events': 0.05,
    'contacts': 0.05,
    'gallery_images': 0.30,
}

# --- Predefined Data for Simulation ---

# App Packages
COMMON_APP_PACKAGES = ['com.whatsapp', 'com.instagram.android', 'com.google.android.youtube',
                       'com.android.chrome', 'com.spotify.music', 'com.facebook.katana']
TRAVEL_APP_PACKAGES = ['com.google.android.apps.maps', 'com.booking.com', 'com.expedia.bookings',
                       'com.tripadvisor.tripadvisor', 'com.uber.android']
FINANCE_APP_PACKAGES = ['com.zerodha.kite', 'com.etmoney.android', 'com.paytm.business']
FITNESS_APP_PACKAGES = ['com.nike.ntc', 'com.myfitnesspal.android', 'com.strava']
LANGUAGE_APP_PACKAGES = ['com.duolingo', 'com.busuu.android.enc', 'com.memrise.android.memrisecompanion']

# Locations (lat, lon, city, state, country)
HOME_LOCATIONS = [
    {"lat": 12.9716, "lon": 77.5946, "city": "Bengaluru", "state": "Karnataka", "country": "India"},
    {"lat": 28.7041, "lon": 77.1025, "city": "New Delhi", "state": "Delhi", "country": "India"},
]

TRAVEL_DESTINATIONS = [
    {"lat": 48.8566, "lon": 2.3522, "city": "Paris", "state": "Ile-de-France", "country": "France", "landmarks": ["Eiffel Tower", "Louvre Museum", "Notre Dame"]},
    {"lat": 35.6762, "lon": 139.6503, "city": "Tokyo", "state": "Tokyo", "country": "Japan", "landmarks": ["Shibuya Crossing", "Tokyo Skytree", "Senso-ji Temple"]},
    {"lat": -33.8688, "lon": 151.2093, "city": "Sydney", "state": "New South Wales", "country": "Australia", "landmarks": ["Sydney Opera House", "Bondi Beach", "Harbour Bridge"]},
    {"lat": 15.2993, "lon": 74.1240, "city": "Goa", "state": "Goa", "country": "India", "landmarks": ["Palolem Beach", "Fort Aguada", "Dudhsagar Falls"]},
]

# CLIP-like Scene Names
HOME_SCENES = ['living room', 'kitchen', 'bedroom', 'garden', 'pet', 'family dinner', 'reading a book', 'working from home']
TRAVEL_SCENES = ['Eiffel Tower', 'Louvre Museum', 'beach', 'mountain view', 'cityscape', 'street food', 'museum interior',
                 'busy market', 'waterfall', 'historic building', 'temple', 'airport', 'airplane interior', 'hotel room']
FINANCE_SCENES = ['stock chart', 'trading desk', 'computer screen with numbers', 'office building']
FITNESS_SCENES = ['gym interior', 'running track', 'yoga studio', 'person exercising', 'healthy meal']
LANGUAGE_SCENES = ['textbook', 'foreign city street sign', 'person speaking', 'classroom']

# Contact and Person Details
CONTACT_NAMES = ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams']
PERSON_GENDERS = ['male', 'female']
PERSON_AGES = list(range(18, 60))

TIME_ZONES = ['America/New_York', 'Europe/London', 'Asia/Kolkata', 'Asia/Tokyo', 'Australia/Sydney']

# --- Helper Functions ---

def generate_timestamp(start_dt, end_dt):
    """Generates a random datetime object within a given range."""
    time_diff = end_dt - start_dt
    random_seconds = random.uniform(0, time_diff.total_seconds())
    return start_dt + timedelta(seconds=random_seconds)

def generate_location(loc_type, city_data=None):
    """Generates a location dictionary based on type."""
    if loc_type == 'home':
        loc = random.choice(HOME_LOCATIONS)
    elif loc_type == 'travel' and city_data:
        loc = city_data
    else: # Default to home if something goes wrong
        loc = random.choice(HOME_LOCATIONS)

    return {
        "lat": loc["lat"] + random.uniform(-0.01, 0.01), # Add slight variation
        "lon": loc["lon"] + random.uniform(-0.01, 0.01),
        "city": loc["city"],
        "state": loc["state"],
        "country": loc["country"]
    }

def get_random_contact_id(user_contacts):
    """Returns an existing contact_id or generates a new one."""
    if random.random() < 0.8 and user_contacts: # 80% chance to pick existing
        return random.choice(list(user_contacts.keys()))
    else:
        new_contact_id = str(uuid.uuid4())
        user_contacts[new_contact_id] = {
            "display_name": random.choice(CONTACT_NAMES),
            "phones": [f"+1{random.randint(1000000000, 9999999999)}"],
            "emails": [f"{random.choice(CONTACT_NAMES).replace(' ', '.').lower()}@example.com"]
        }
        return new_contact_id

def get_random_person_id(user_persons):
    """Returns an existing person_id or generates a new one."""
    if random.random() < 0.7 and user_persons: # 70% chance to pick existing
        return random.choice(list(user_persons.keys()))
    else:
        new_person_id = str(uuid.uuid4())
        user_persons[new_person_id] = {
            "gender": random.choice(PERSON_GENDERS),
            "age": random.choice(PERSON_AGES)
        }
        return new_person_id

# --- Data Generation Functions for Each Modality ---

def generate_app_usage(timestamp, current_location_data, app_list, event_type_list, time_zone):
    return {
        "identifier": str(uuid.uuid4()),
        "timestamp": timestamp.isoformat(),
        "duration": random.randint(10, 3600), # seconds
        "package_name": random.choice(app_list),
        "event_type": random.choice(event_type_list),
        "time_zone": time_zone
    }

def generate_call_log(timestamp, current_location_data, user_contacts, time_zone):
    contact_id = get_random_contact_id(user_contacts)
    return {
        "identifier": str(uuid.uuid4()),
        "date": timestamp.isoformat(),
        "type": random.choice(['incoming', 'outgoing', 'missed']),
        "geocoded_loc": generate_location('home', current_location_data), # Calls often from home or current location
        "duration": random.randint(10, 1200), # seconds
        "number": user_contacts[contact_id]["phones"][0],
        "contact_id": contact_id,
        "call_rec": random.choice([True, False]),
        "call_rec_transcript": "Dummy transcript text.",
        "ai_summary": "Dummy AI summary.",
        "ai_keywords": random.sample(['meeting', 'family', 'work', 'friends', 'travel plans'], k=random.randint(1, 3)),
        "entities": random.sample(['person_name', 'organization', 'location'], k=random.randint(0, 2))
    }

def generate_calendar_event(timestamp, current_location_data, user_contacts, time_zone):
    start_date = timestamp
    end_date = start_date + timedelta(hours=random.randint(1, 4))
    attendees = [get_random_contact_id(user_contacts) for _ in range(random.randint(0, 2))]
    reminders = [start_date - timedelta(minutes=random.randint(10, 60))] if random.random() < 0.5 else []
    return {
        "identifier": str(uuid.uuid4()),
        "idnum": random.randint(10000, 99999),
        "title": random.choice(['Meeting', 'Appointment', 'Birthday', 'Travel Planning', 'Workout']),
        "description": "Dummy event description.",
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
        "location": random.choice([current_location_data["city"], "Online", "Client Office"]),
        "organizer": "user_self",
        "attendees": attendees,
        "reminders": [r.isoformat() for r in reminders]
    }

def generate_contact(timestamp, user_contacts, time_zone):
    contact_id = get_random_contact_id(user_contacts) # This will create a new one if not picked
    contact_info = user_contacts[contact_id]
    return {
        "identifier": str(uuid.uuid4()),
        "last_updated": timestamp.isoformat(),
        "display_name": contact_info["display_name"],
        "photo_uri": random.choice([True, False]),
        "contact_id": contact_id,
        "phones": contact_info["phones"],
        "normalized_num": [p.replace('+', '').replace(' ', '') for p in contact_info["phones"]],
        "names": [{"first": contact_info["display_name"].split()[0], "last": contact_info["display_name"].split()[-1]}],
        "emails": contact_info["emails"]
    }

def generate_gallery_image(timestamp, current_location_data, scene_list, user_persons, time_zone):
    num_people = random.randint(0, 3)
    person_data = []
    for _ in range(num_people):
        person_id = get_random_person_id(user_persons)
        person_info = user_persons[person_id]
        person_data.append({
            "person_id": person_id,
            "gender": person_info["gender"],
            "age": person_info["age"],
            "bounding_box": [random.randint(0, 500), random.randint(0, 500),
                             random.randint(501, 1000), random.randint(501, 1000)] # [x1, y1, x2, y2]
        })

    return {
        "identifier": str(uuid.uuid4()),
        "person_id": person_data,
        "timestamp": timestamp.isoformat(),
        "location": generate_location('travel' if current_location_data['city'] not in [h['city'] for h in HOME_LOCATIONS] else 'home', current_location_data),
        "scene_name": random.sample(scene_list, k=random.randint(1, min(3, len(scene_list)))),
        "time_zone": time_zone
    }

# --- Daily Simulation Functions ---

def simulate_day_events(user_id, current_date, events_per_day_map, location_data,
                        app_packages, scene_list, user_contacts, user_persons, time_zone, all_data):
    """Simulates events for a single day based on specified rates and contexts."""
    day_start = current_date
    day_end = current_date + timedelta(days=1)

    for modality, count in events_per_day_map.items():
        for _ in range(int(count)):
            timestamp = generate_timestamp(day_start, day_end)
            if modality == 'app_usage':
                event_type_list = ['foreground', 'background', 'notification_click']
                all_data['app_usage'].append(generate_app_usage(timestamp, location_data, app_packages, event_type_list, time_zone))
            elif modality == 'call_log':
                all_data['call_log'].append(generate_call_log(timestamp, location_data, user_contacts, time_zone))
            elif modality == 'calendar_events':
                all_data['calendar_events'].append(generate_calendar_event(timestamp, location_data, user_contacts, time_zone))
            elif modality == 'contacts':
                all_data['contacts'].append(generate_contact(timestamp, user_contacts, time_zone))
            elif modality == 'gallery_images':
                all_data['gallery_images'].append(generate_gallery_image(timestamp, location_data, scene_list, user_persons, time_zone))

def simulate_baseline_day(user_id, current_date, home_location, user_contacts, user_persons, time_zone, all_data):
    events_per_day = {
        'app_usage': BASE_APP_USAGE_PER_DAY,
        'call_log': BASE_CALL_LOG_PER_DAY,
        'calendar_events': BASE_CALENDAR_PER_DAY,
        'contacts': BASE_CONTACT_PER_DAY,
        'gallery_images': BASE_GALLERY_PER_DAY,
    }
    simulate_day_events(user_id, current_date, events_per_day, home_location,
                        COMMON_APP_PACKAGES, HOME_SCENES, user_contacts, user_persons, time_zone, all_data)

def simulate_travel_day(user_id, current_date, travel_destination_data, user_contacts, user_persons, time_zone, all_data):
    events_per_day = {
        'app_usage': BASE_APP_USAGE_PER_DAY * TRAVEL_APP_MULTIPLIER,
        'call_log': BASE_CALL_LOG_PER_DAY * TRAVEL_CALL_MULTIPLIER,
        'calendar_events': BASE_CALENDAR_PER_DAY, # Calendar might not change much daily during travel
        'contacts': BASE_CONTACT_PER_DAY,
        'gallery_images': BASE_GALLERY_PER_DAY * TRAVEL_GALLERY_MULTIPLIER,
    }
    simulate_day_events(user_id, current_date, events_per_day, travel_destination_data,
                        COMMON_APP_PACKAGES + TRAVEL_APP_PACKAGES, TRAVEL_SCENES, user_contacts, user_persons, time_zone, all_data)

def simulate_interest_day(user_id, current_date, interest_type, home_location, user_contacts, user_persons, time_zone, all_data):
    app_list = COMMON_APP_PACKAGES
    scene_list = HOME_SCENES
    if interest_type == 'finance':
        app_list = COMMON_APP_PACKAGES + FINANCE_APP_PACKAGES
        scene_list = HOME_SCENES + FINANCE_SCENES
    elif interest_type == 'fitness':
        app_list = COMMON_APP_PACKAGES + FITNESS_APP_PACKAGES
        scene_list = HOME_SCENES + FITNESS_SCENES
    elif interest_type == 'language':
        app_list = COMMON_APP_PACKAGES + LANGUAGE_APP_PACKAGES
        scene_list = HOME_SCENES + LANGUAGE_SCENES

    events_per_day = {
        'app_usage': BASE_APP_USAGE_PER_DAY * INTEREST_APP_MULTIPLIER,
        'call_log': BASE_CALL_LOG_PER_DAY * INTEREST_CALL_MULTIPLIER,
        'calendar_events': BASE_CALENDAR_PER_DAY,
        'contacts': BASE_CONTACT_PER_DAY,
        'gallery_images': BASE_GALLERY_PER_DAY * INTEREST_GALLERY_MULTIPLIER,
    }
    simulate_day_events(user_id, current_date, events_per_day, home_location,
                        app_list, scene_list, user_contacts, user_persons, time_zone, all_data)


# --- Main Simulation Logic ---

def simulate_user_data(user_id):
    user_data = {
        "user_id": user_id,
        "travel_events": [],
        "interest_changes": [],
        "all_simulated_data": {
            "app_usage": [],
            "call_log": [],
            "calendar_events": [],
            "contacts": [],
            "gallery_images": []
        }
    }

    # Initialize user-specific data pools
    user_contacts = {} # Stores contact_id -> contact_info
    user_persons = {} # Stores person_id -> person_info
    user_home_location = random.choice(HOME_LOCATIONS)
    user_time_zone = random.choice(TIME_ZONES)

    # Schedule Travel Events (2 per user)
    travel_schedules = []
    for i in range(2):
        # Ensure travel periods don't overlap significantly
        while True:
            travel_start_day_idx = random.randint(30, SIM_DAYS - (TRAVEL_TRIGGER_DURATION + TRAVEL_GROWING_DURATION + TRAVEL_DECAY_DURATION) - 30)
            travel_end_day_idx = travel_start_day_idx + TRAVEL_TRIGGER_DURATION + TRAVEL_GROWING_DURATION + TRAVEL_DECAY_DURATION

            overlap = False
            # Iterate over existing schedules, unpacking 3 values for existing_start, existing_end, and the ignored third element
            for existing_start, existing_end, _ in travel_schedules:
                if not (travel_end_day_idx < existing_start or travel_start_day_idx > existing_end):
                    overlap = True
                    break
            if not overlap:
                travel_destination = random.choice(TRAVEL_DESTINATIONS) # Choose destination here
                travel_schedules.append((travel_start_day_idx, travel_end_day_idx, travel_destination)) # Append the 3-element tuple
                break

    # Schedule Interest Change Event (1 per user)
    interest_schedules = []
    while True:
        interest_start_day_idx = random.randint(30, SIM_DAYS - (INTEREST_TRIGGER_DURATION + INTEREST_GROWING_DURATION + INTEREST_STABLE_DURATION) - 30)
        interest_end_day_idx = interest_start_day_idx + INTEREST_TRIGGER_DURATION + INTEREST_GROWING_DURATION + INTEREST_STABLE_DURATION

        overlap = False
        for existing_start, existing_end, _ in travel_schedules: # Check against travel schedules (which now correctly store 3 elements)
            if not (interest_end_day_idx < existing_start or interest_start_day_idx > existing_end):
                overlap = True
                break
        if not overlap:
            interest_type = random.choice(['finance', 'fitness', 'language'])
            interest_schedules.append((interest_start_day_idx, interest_end_day_idx, interest_type))
            break

    # Sort schedules to process chronologically
    all_events_schedule = []
    for idx, (start, end, dest) in enumerate(travel_schedules):
        all_events_schedule.append({
            "type": "travel",
            "id": f"travel_{idx+1}",
            "start_day": start,
            "end_day": end,
            "destination": dest
        })
    for idx, (start, end, int_type) in enumerate(interest_schedules):
        all_events_schedule.append({
            "type": "interest",
            "id": f"interest_{idx+1}",
            "start_day": start,
            "end_day": end,
            "interest_type": int_type
        })
    all_events_schedule.sort(key=lambda x: x["start_day"])


    # Main Simulation Loop
    for day_idx in range(SIM_DAYS):
        current_date = START_DATE + timedelta(days=day_idx)
        current_location_for_day = user_home_location # Default to home
        current_app_list = COMMON_APP_PACKAGES
        current_scene_list = HOME_SCENES

        active_event = None
        for event in all_events_schedule:
            if event["start_day"] <= day_idx < event["end_day"]:
                active_event = event
                break # Prioritize events if there's any overlap (though we tried to avoid)

        if active_event and active_event["type"] == "travel":
            travel_id = active_event["id"]
            travel_destination = active_event["destination"]

            # Determine travel phase and update GT
            if day_idx == active_event["start_day"]: # Trigger day
                phase_name = "trigger"
                user_data["travel_events"].append({
                    "travel_id": travel_id,
                    "destination_city": travel_destination["city"],
                    "phases": {
                        "trigger": {"start_date": current_date.isoformat(), "end_date": (current_date + timedelta(days=TRAVEL_TRIGGER_DURATION)).isoformat(), "trigger_event_type": "Calendar Event: Trip to " + travel_destination["city"]}
                    }
                })
                simulate_baseline_day(user_id, current_date, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])
            elif active_event["start_day"] < day_idx < active_event["start_day"] + TRAVEL_TRIGGER_DURATION + TRAVEL_GROWING_DURATION: # Growing phase
                phase_name = "growing"
                current_location_for_day = travel_destination
                user_data["travel_events"][-1]["phases"]["growing"] = {"start_date": (START_DATE + timedelta(days=active_event["start_day"] + TRAVEL_TRIGGER_DURATION)).isoformat(), "end_date": (START_DATE + timedelta(days=active_event["start_day"] + TRAVEL_TRIGGER_DURATION + TRAVEL_GROWING_DURATION)).isoformat()}
                simulate_travel_day(user_id, current_date, travel_destination, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])
            else: # Decay phase
                phase_name = "decay"
                user_data["travel_events"][-1]["phases"]["decay"] = {"start_date": (START_DATE + timedelta(days=active_event["start_day"] + TRAVEL_TRIGGER_DURATION + TRAVEL_GROWING_DURATION)).isoformat(), "end_date": (START_DATE + timedelta(days=active_event["end_day"])).isoformat()}
                simulate_baseline_day(user_id, current_date, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"]) # Back to home activity

            # Add a specific trigger event on the trigger day
            if day_idx == active_event["start_day"]:
                # Example: Add a specific calendar event for travel trigger
                trigger_ts = generate_timestamp(current_date, current_date + timedelta(days=1))
                user_data["all_simulated_data"]["calendar_events"].append({
                    "identifier": str(uuid.uuid4()),
                    "idnum": random.randint(10000, 99999),
                    "title": f"Trip to {travel_destination['city']} Planning",
                    "description": "Travel planning event (simulated trigger).",
                    "start_date": trigger_ts.isoformat(),
                    "end_date": (trigger_ts + timedelta(hours=1)).isoformat(),
                    "location": "Home",
                    "organizer": "user_self",
                    "attendees": [],
                    "reminders": []
                })
                # Or a specific image with new location tag:
                user_data["all_simulated_data"]["gallery_images"].append(generate_gallery_image(
                    trigger_ts, travel_destination, ['travel documents', 'map screenshot'], user_persons, user_time_zone
                ))

        elif active_event and active_event["type"] == "interest":
            interest_id = active_event["id"]
            interest_type = active_event["interest_type"]

            # Determine interest phase and update GT
            if day_idx == active_event["start_day"]: # Trigger day
                phase_name = "trigger"
                user_data["interest_changes"].append({
                    "interest_id": interest_id,
                    "interest_type": interest_type,
                    "phases": {
                        "trigger": {"start_date": current_date.isoformat(), "end_date": (current_date + timedelta(days=INTEREST_TRIGGER_DURATION)).isoformat(), "trigger_event_type": f"App Usage Surge: {interest_type.capitalize()} Apps"}
                    }
                })
                simulate_baseline_day(user_id, current_date, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])
            elif active_event["start_day"] < day_idx < active_event["start_day"] + INTEREST_TRIGGER_DURATION + INTEREST_GROWING_DURATION: # Growing phase
                phase_name = "growing"
                user_data["interest_changes"][-1]["phases"]["growing"] = {"start_date": (START_DATE + timedelta(days=active_event["start_day"] + INTEREST_TRIGGER_DURATION)).isoformat(), "end_date": (START_DATE + timedelta(days=active_event["start_day"] + INTEREST_TRIGGER_DURATION + INTEREST_GROWING_DURATION)).isoformat()}
                simulate_interest_day(user_id, current_date, interest_type, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])
            else: # Stable phase
                phase_name = "stable"
                user_data["interest_changes"][-1]["phases"]["stable"] = {"start_date": (START_DATE + timedelta(days=active_event["start_day"] + INTEREST_TRIGGER_DURATION + INTEREST_GROWING_DURATION)).isoformat(), "end_date": (START_DATE + timedelta(days=active_event["end_day"])).isoformat()}
                simulate_interest_day(user_id, current_date, interest_type, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])

            # Add a specific trigger event on the trigger day
            if day_idx == active_event["start_day"]:
                # Example: Add a surge in specific app usage for interest trigger
                trigger_ts = generate_timestamp(current_date, current_date + timedelta(days=1))
                app_list_for_trigger = []
                if interest_type == 'finance': app_list_for_trigger = FINANCE_APP_PACKAGES
                elif interest_type == 'fitness': app_list_for_trigger = FITNESS_APP_PACKAGES
                elif interest_type == 'language': app_list_for_trigger = LANGUAGE_APP_PACKAGES

                for _ in range(5): # 5 extra app usage events
                    user_data["all_simulated_data"]["app_usage"].append(generate_app_usage(
                        trigger_ts, user_home_location, app_list_for_trigger, ['foreground'], user_time_zone
                    ))
                # Or a specific image with new scene tag:
                scene_for_trigger = []
                if interest_type == 'finance': scene_for_trigger = ['stock chart']
                elif interest_type == 'fitness': scene_for_trigger = ['gym interior']
                elif interest_type == 'language': scene_for_trigger = ['foreign city street sign']
                user_data["all_simulated_data"]["gallery_images"].append(generate_gallery_image(
                    trigger_ts, user_home_location, scene_for_trigger, user_persons, user_time_zone
                ))

        else: # Baseline activity
            simulate_baseline_day(user_id, current_date, user_home_location, user_contacts, user_persons, user_time_zone, user_data["all_simulated_data"])

    return user_data

# --- Run Simulation ---
if __name__ == "__main__":
    all_users_simulated_data = []
    for i in range(N_USERS):
        print(f"Simulating data for User {i+1}...")
        user_id = f"user_{i+1}"
        user_data = simulate_user_data(user_id)
        all_users_simulated_data.append(user_data)
        print(f"User {i+1} simulation complete. Total events: {sum(len(v) for v in user_data['all_simulated_data'].values())}")

    # Output the simulated data to a JSON file
    output_filename = "simulated_smartphone_data.json"
    with open(output_filename, 'w') as f:
        json.dump(all_users_simulated_data, f, indent=4)

    print(f"\nSimulation complete for {N_USERS} users. Data saved to {output_filename}")
    print("Example GT for first user:")
    print(json.dumps(all_users_simulated_data[0]['travel_events'], indent=2))
    print(json.dumps(all_users_simulated_data[0]['interest_changes'], indent=2))

import json
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the simulated data
try:
    with open("simulated_smartphone_data.json", 'r') as f:
        all_users_data = json.load(f)
except FileNotFoundError:
    print("Error: simulated_smartphone_data.json not found. Please run the simulation code first.")
    exit()

# --- Data Processing for Visualization ---

def parse_iso_date(iso_str):
    """Parses an ISO format string to a datetime object."""
    return datetime.fromisoformat(iso_str)

def get_phase_info(event_type, event_gt, current_timestamp):
    """Determines which phase an event falls into."""
    for phase_name, phase_dates in event_gt['phases'].items():
        start_date = parse_iso_date(phase_dates['start_date'])
        end_date = parse_iso_date(phase_dates['end_date'])
        if start_date <= current_timestamp < end_date:
            return phase_name
    return "baseline" # If not in any specific phase, it's baseline

def analyze_activity_by_phase(user_data):
    """Analyzes activity counts for each modality across different phases."""
    activity_counts = []

    # Get all events and their timestamps, and add modality type
    all_events = []
    for modality, events in user_data['all_simulated_data'].items():
        for event in events:
            timestamp_str = event.get('timestamp') or event.get('date') or event.get('start_date')
            if timestamp_str:
                all_events.append({
                    'modality': modality,
                    'timestamp': parse_iso_date(timestamp_str)
                })

    for event_data in all_events:
        timestamp = event_data['timestamp']
        modality = event_data['modality']

        # Check against travel events
        current_travel_phase = "baseline"
        for travel_event_gt in user_data['travel_events']:
            phase = get_phase_info('travel', travel_event_gt, timestamp)
            if phase != "baseline":
                current_travel_phase = phase
                break # Assume one active travel event at a time

        # Check against interest changes
        current_interest_phase = "baseline"
        for interest_event_gt in user_data['interest_changes']:
            phase = get_phase_info('interest', interest_event_gt, timestamp)
            if phase != "baseline":
                current_interest_phase = phase
                break # Assume one active interest event at a time

        # Determine the overall "active" phase for the event
        # Prioritize travel over interest, then interest over baseline
        active_phase = "baseline"
        if current_travel_phase != "baseline":
            # Append destination city to travel phase for clarity in plot
            travel_destination_city = next((t['destination_city'] for t in user_data['travel_events'] if get_phase_info('travel', t, timestamp) == current_travel_phase), "")
            active_phase = f"Travel ({current_travel_phase}) - {travel_destination_city}"
        elif current_interest_phase != "baseline":
            # Append interest type to interest phase for clarity in plot
            interest_type = next((i['interest_type'] for i in user_data['interest_changes'] if get_phase_info('interest', i, timestamp) == current_interest_phase), "")
            active_phase = f"Interest ({current_interest_phase}) - {interest_type.capitalize()}"

        activity_counts.append({
            'modality': modality,
            'phase': active_phase,
            'user_id': user_data['user_id']
        })

    return pd.DataFrame(activity_counts)

# --- Generate Plots ---

all_activity_dfs = []
for user_data in all_users_data:
    all_activity_dfs.append(analyze_activity_by_phase(user_data))

combined_df = pd.concat(all_activity_dfs)

# Calculate counts for plotting
plot_data = combined_df.groupby(['user_id', 'phase', 'modality']).size().reset_index(name='count')

# Ensure all phases are present for consistent plotting, even if count is 0
# Create a full index of all possible (user_id, phase, modality) combinations
# Dynamically collect all unique phases that appeared in the data
unique_phases_in_data = combined_df['phase'].unique()
all_modalities = list(MODALITY_PROBS.keys())
all_users = combined_df['user_id'].unique()

full_index = pd.MultiIndex.from_product([all_users, unique_phases_in_data, all_modalities], names=['user_id', 'phase', 'modality'])
plot_data = plot_data.set_index(['user_id', 'phase', 'modality']).reindex(full_index, fill_value=0).reset_index()


# Order phases for better visualization
# This order needs to be dynamic based on the actual destinations/interests
# We'll create a custom sort key for phases
def custom_phase_sort_key(phase_name):
    if phase_name == "baseline":
        return 0
    elif "Travel" in phase_name:
        if "trigger" in phase_name: return 1
        if "growing" in phase_name: return 2
        if "decay" in phase_name: return 3
    elif "Interest" in phase_name:
        if "trigger" in phase_name: return 4
        if "growing" in phase_name: return 5
        if "stable" in phase_name: return 6
    return 99 # Fallback for unexpected phases

plot_data['phase_sort_order'] = plot_data['phase'].apply(custom_phase_sort_key)
plot_data = plot_data.sort_values(by=['user_id', 'phase_sort_order', 'phase', 'modality']).drop(columns='phase_sort_order')

# Now convert 'phase' to categorical with the determined order
plot_data['phase'] = pd.Categorical(plot_data['phase'], categories=plot_data['phase'].unique(), ordered=True)


plt.figure(figsize=(18, 10))
sns.set_theme(style="whitegrid")

g = sns.catplot(
    data=plot_data,
    x="phase",
    y="count",
    hue="modality",
    col="user_id",
    kind="bar",
    col_wrap=2,
    height=6,
    aspect=1.5,
    palette="viridis",
    legend_out=True # Ensure legend is outside if many hues
)

g.set_axis_labels("Phase", "Activity Count")
g.set_titles("User: {col_name}")
g.set_xticklabels(rotation=45, ha="right")
g.fig.suptitle("Activity Counts by Modality and Phase for Each User", y=1.02, fontsize=16) # Adjust y for title

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent title overlap
plt.show()

