# -*- coding: utf-8 -*-
"""simulation-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0Tt4WVZeFibdwkYDv6mj_bRncTje4Ab
"""

pip install faker

import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import random
from faker import Faker
from collections import defaultdict

# -------- User Generator --------
def auto_generate_users(n=5):
    fake = Faker()
    cities = ['New York', 'London', 'Tokyo', 'Delhi', 'São Paulo', 'Paris', 'Sydney']
    interests = ['fitness', 'travel', 'social', 'cooking', 'gaming', 'education', 'mental_health', 'family']
    trends = ['growing', 'decaying', 'stable']
    scenarios = ['normal_day', 'festival', 'conference', 'exam', 'vacation']

    users = []
    for i in range(n):
        interests_sample = random.sample(interests, k=4)
        interest_pref = {k: random.choice(trends) for k in interests_sample}

        users.append({
            'user_id': f'u{i}',
            'age': random.randint(18, 60),
            'gender': random.choice(['M', 'F', 'Non-binary']),
            'married': random.choice([True, False]),
            'working': random.choice([True, False]),
            'studying': random.choice([True, False]),
            'city': random.choice(cities),
            'important_contacts': [fake.first_name() for _ in range(3)],
            'favorite_apps': random.sample(['Instagram', 'WhatsApp', 'Strava', 'Slack', 'YouTube', 'Teams', 'Zoom', 'Twitter'], k=4),
            'interest_pref': interest_pref,
            'personality': random.choice(['morning_person', 'night_owl', 'flexible']),
            'scenarios': random.sample(scenarios, k=2)
        })
    return users

# -------- Utility --------
def create_event(event_type, day, start_hour, duration_hours=1):
    start_time = day + timedelta(hours=start_hour)
    end_time = start_time + timedelta(hours=duration_hours)
    return {
        "type": event_type,
        "start_time": start_time,
        "end_time": end_time
    }

# -------- Simulators --------
def simulate_events_by_trend(event_type, trend, start_date, days=60):
    events = []
    current = 0
    for day in range(days):
        base_day = start_date + timedelta(days=day)
        if trend == 'growing':
            prob = min(0.1 + 0.01 * day, 0.9)
        elif trend == 'decaying':
            prob = max(0.9 - 0.01 * day, 0.05)
        else:  # stable
            prob = 0.3
        if random.random() < prob:
            events.append(create_event(event_type, base_day, random.randint(7, 22), random.choice([1, 2])))
    return events

def simulate_routine(personality, start_date, days=60):
    events = []
    for day in range(days):
        date = start_date + timedelta(days=day)
        if personality == 'morning_person':
            events.append(create_event("routine", date, random.randint(6, 9)))
        elif personality == 'night_owl':
            events.append(create_event("routine", date, random.randint(20, 23)))
        else:
            events.append(create_event("routine", date, random.randint(10, 22)))
    return events

def simulate_communication(start_date, days=60, mu=0.2, alpha=0.8, beta=1.2):
    t = 0
    events = []
    timestamps = []
    while t < days:
        lambda_t = mu + sum([alpha * np.exp(-beta * (t - e)) for e in timestamps])
        w = -np.log(np.random.rand()) / lambda_t
        t += w
        if t >= days:
            break
        e_day = start_date + timedelta(days=int(t))
        events.append(create_event("communication", e_day, random.randint(9, 22)))
        timestamps.append(t)
    return events

# -------- Master Timeline Generator --------
def simulate_user_life(user, start_date, days=60):
    all_events = []
    for interest, trend in user['interest_pref'].items():
        all_events += simulate_events_by_trend(interest, trend, start_date, days)
    all_events += simulate_routine(user['personality'], start_date, days)
    all_events += simulate_communication(start_date, days)
    return sorted(all_events, key=lambda x: x['start_time'])

# -------- Plotter --------
def plot_user_timeline(events, user_id):
    grouped = defaultdict(list)
    for e in events:
        grouped[e['type']].append((e['start_time'], e['end_time']))

    fig, ax = plt.subplots(figsize=(12, 6))
    event_types = list(grouped.keys())
    for i, etype in enumerate(event_types):
        for (start, end) in grouped[etype]:
            ax.plot([start, end], [i, i], lw=4, label=etype if i == 0 else "", alpha=0.7)

    ax.set_yticks(range(len(event_types)))
    ax.set_yticklabels(event_types)
    ax.set_title(f"Timeline of Life Events for {user_id}")
    ax.set_xlabel("Date")
    ax.grid(True, axis='x', linestyle='--', alpha=0.3)
    plt.tight_layout()
    plt.show()

# -------- Simulate One User for Demo --------
users = auto_generate_users(1)
user = users[0]
start_date = datetime(2025, 7, 1)
events = simulate_user_life(user, start_date, days=60)
plot_user_timeline(events, user['user_id'])

#
import pandas as pd
import json

# -------- Convert event list to DataFrame --------
def events_to_dataframe(user, events):
    rows = []
    for e in events:
        rows.append({
            "user_id": user["user_id"],
            "age": user["age"],
            "gender": user["gender"],
            "city": user["city"],
            "working": user["working"],
            "studying": user["studying"],
            "personality": user["personality"],
            "event_type": e["type"],
            "start_time": e["start_time"],
            "end_time": e["end_time"],
            "duration_hours": (e["end_time"] - e["start_time"]).total_seconds() / 3600,
            "ground_truth_trend": user["interest_pref"].get(e["type"], "N/A")  # if not interest-based event
        })
    return pd.DataFrame(rows)

# -------- Simulate Multiple Users and Collect Events --------
all_users = auto_generate_users(5)
all_event_dfs = []

for user in all_users:
    events = simulate_user_life(user, start_date=datetime(2025, 7, 1), days=60)
    df = events_to_dataframe(user, events)
    all_event_dfs.append(df)

# -------- Combine and Export --------
combined_df = pd.concat(all_event_dfs, ignore_index=True)
csv_path = "/mnt/data/user_life_event_log.csv"
json_path = "/mnt/data/user_life_event_log.json"

combined_df.to_csv(csv_path, index=False)
combined_df.to_json(json_path, orient="records", date_format="iso")

csv_path, json_path

import numpy as np
import pandas as pd
import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()

# ---- Constants ----
MODALITIES = ['gps', 'accelerometer', 'apps', 'camera', 'mic', 'screen', 'bluetooth']
LOCATIONS = ['New York, USA', 'London, UK', 'Tokyo, Japan', 'Delhi, India', 'Paris, France']
SCENES = ['kitchen', 'classroom', 'gym', 'office', 'street', 'cafe', 'living room']
FACES = ['family', 'friend', 'colleague']

# ---- Simulation Functions ----

def simulate_time_series(days, trend='stable', base_rate=3):
    timestamps = []
    for day in range(days):
        if trend == 'growing':
            rate = base_rate + 0.1 * day
        elif trend == 'decaying':
            rate = max(base_rate - 0.05 * day, 0.5)
        else:  # stable
            rate = base_rate
        count = np.random.poisson(rate)
        for _ in range(count):
            hour = random.randint(6, 23)
            timestamps.append((day, hour))
    return timestamps

def simulate_gps_location():
    lat = round(random.uniform(-90, 90), 6)
    lon = round(random.uniform(-180, 180), 6)
    city_info = random.choice(LOCATIONS).split(", ")
    return {
        'lat': lat,
        'lon': lon,
        'city': city_info[0],
        'state': 'N/A',
        'country': city_info[1]
    }

def simulate_faces():
    faces = []
    num_faces = random.randint(0, 3)
    for i in range(num_faces):
        faces.append({
            'id': f'face_{i}',
            'gender': random.choice(['M', 'F']),
            'age': random.randint(5, 70),
            'bbox': [random.randint(0, 100), random.randint(0, 100), 50, 50],
            'relation': random.choice(FACES)
        })
    return faces

def simulate_camera_event():
    return {
        'location': simulate_gps_location(),
        'faces': simulate_faces(),
        'scene': random.choice(SCENES)
    }

def simulate_daily_modality(user, day, trend_map):
    day_data = {'user_id': user['user_id'], 'day': day}

    for modality in MODALITIES:
        trend = trend_map.get(modality, 'stable')
        timestamps = simulate_time_series(1, trend)
        if modality == 'gps':
            day_data['gps'] = [simulate_gps_location() for _ in timestamps]
        elif modality == 'accelerometer':
            day_data['accelerometer'] = [{'x': round(random.gauss(0, 1), 2),
                                          'y': round(random.gauss(0, 1), 2),
                                          'z': round(random.gauss(9.8, 1), 2)} for _ in timestamps]
        elif modality == 'apps':
            day_data['apps'] = random.sample(user['favorite_apps'], k=random.randint(1, len(user['favorite_apps'])))
        elif modality == 'camera':
            day_data['camera'] = [simulate_camera_event() for _ in timestamps]
        elif modality == 'mic':
            day_data['mic'] = [{'duration_sec': random.randint(2, 300)} for _ in timestamps]
        elif modality == 'screen':
            day_data['screen'] = [{'screen_on': random.randint(5, 30)} for _ in timestamps]
        elif modality == 'bluetooth':
            day_data['bluetooth'] = [{'device': fake.word(), 'strength': round(random.uniform(-90, -30), 1)} for _ in timestamps]

        # Ground truth pattern label
        day_data[f'{modality}_pattern'] = trend

    return day_data

# ---- Generate full timeline data for multiple users ----

def simulate_smartphone_timeline(users, days=7):
    timeline_data = []
    for user in users:
        trend_map = {
            'gps': random.choice(['growing', 'decaying', 'stable']),
            'accelerometer': random.choice(['growing', 'decaying', 'stable']),
            'apps': random.choice(['growing', 'decaying', 'stable']),
            'camera': random.choice(['growing', 'decaying', 'stable']),
            'mic': random.choice(['growing', 'decaying', 'stable']),
            'screen': random.choice(['growing', 'decaying', 'stable']),
            'bluetooth': random.choice(['growing', 'decaying', 'stable']),
        }
        for day in range(days):
            day_record = simulate_daily_modality(user, day, trend_map)
            timeline_data.append(day_record)
    return timeline_data

# ---- Simulate and Export ----

sim_users = auto_generate_users(3)
timeline = simulate_smartphone_timeline(sim_users, days=7)

# Save JSON
# json_path = "/mnt/data/smartphone_multimodal_timeline.json"
# with open(json_path, "w") as f:
#     json.dump(timeline, f, indent=2, default=str)

# json_path
print(timeline)

import json

# --------------------------- Modality Templates --------------------------- #

def simulate_app_usage(user, day, trend):
    entries = simulate_time_series(1, trend)
    return [{
        "timestamp": str(datetime(2025, 7, 1) + timedelta(days=day, hours=h)),
        "package_name": random.choice(user["favorite_apps"]),
        "event_type": random.choice(["start", "stop", "notification"]),
        "time_zone": "Asia/Kolkata"
    } for _, h in entries]

def simulate_call_log(user, day, trend):
    entries = simulate_time_series(1, trend)
    return [{
        "identifier": fake.uuid4(),
        "date": str(datetime(2025, 7, 1) + timedelta(days=day, hours=h)),
        "type": random.choice(["incoming", "outgoing", "missed"]),
        "geocoded_loc": simulate_gps_location(),
        "duration": random.randint(10, 300),
        "number": fake.phone_number(),
        "contact_id": fake.uuid4(),
        "call_rec": random.choice([True, False]),
        "call_rec_transcript": fake.sentence(),
        "ai_summary": fake.sentence(),
        "ai_keywords": fake.words(3),
        "entities": fake.words(2)
    } for _, h in entries]

def simulate_calendar_events(day, trend):
    entries = simulate_time_series(1, trend)
    return [{
        "identifier": fake.uuid4(),
        "idnum": random.randint(1000, 9999),
        "title": fake.sentence(nb_words=4),
        "description": fake.sentence(),
        "start_date": str(datetime(2025, 7, 1) + timedelta(days=day, hours=h)),
        "end_date": str(datetime(2025, 7, 1) + timedelta(days=day, hours=h + 1)),
        "location": fake.city(),
        "organizer": fake.name(),
        "attendees": [fake.name() for _ in range(random.randint(1, 3))],
        "reminders": [random.randint(10, 60)]
    } for _, h in entries]

def simulate_contacts(user):
    return [{
        "identifier": fake.uuid4(),
        "last_updated": str(datetime.now()),
        "display_name": fake.name(),
        "photo_uri": "content://photo/uri",
        "contact_id": fake.uuid4(),
        "phones": [fake.phone_number() for _ in range(random.randint(1, 2))],
        "normalized_num": fake.phone_number(),
        "names": [fake.name() for _ in range(2)],
        "emails": [fake.email()]
    } for _ in range(random.randint(2, 4))]

def simulate_gallery(day, trend):
    entries = simulate_time_series(1, trend)
    return [{
        "person_id": f"p{random.randint(1, 5)}",
        "gender": random.choice(["M", "F"]),
        "age": random.randint(3, 70),
        "app_category": random.choice(["camera", "gallery", "chat"]),
        "timestamp": str(datetime(2025, 7, 1) + timedelta(days=day, hours=h)),
        "location": simulate_gps_location(),
        "bounding_box": [random.randint(0, 100), random.randint(0, 100), 50, 50],
        "scene": random.choice(SCENES)
    } for _, h in entries]

# --------------------------- Full Day Simulation --------------------------- #

def simulate_day_for_user(user, day, trend_map):
    return {
        "user_id": user["user_id"],
        "day": day,
        "app_usage": simulate_app_usage(user, day, trend_map["apps"]),
        "call_logs": simulate_call_log(user, day, trend_map["calls"]),
        "calendar": simulate_calendar_events(day, trend_map["calendar"]),
        "contacts": simulate_contacts(user),
        "gallery": simulate_gallery(day, trend_map["gallery"]),
        "pattern_labels": trend_map  # ground truth trends for each modality
    }

# --------------------------- Full Timeline Simulation --------------------------- #

def simulate_user_phone_data(users, days=3):
    all_data = []
    for user in users:
        trend_map = {
            "apps": random.choice(['growing', 'decaying', 'stable']),
            "calls": random.choice(['growing', 'decaying', 'stable']),
            "calendar": random.choice(['growing', 'decaying', 'stable']),
            "gallery": random.choice(['growing', 'decaying', 'stable']),
        }
        for day in range(days):
            daily_data = simulate_day_for_user(user, day, trend_map)
            all_data.append(daily_data)
    return all_data

# --------------------------- Generate & Export --------------------------- #

users = auto_generate_users(3)
smartphone_data = simulate_user_phone_data(users, days=3)

# Save JSON
json_output_path = "/mnt/data/multimodal_smartphone_data_detailed.json"
with open(json_output_path, "w") as f:
    json.dump(smartphone_data, f, indent=2, default=str)

json_output_path

