# -*- coding: utf-8 -*-
"""simulation_portal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zCb_XeDGwn7QhYsU6L5cuDUlQoMrIqb
"""

import numpy as np
from datetime import datetime, timedelta
import random
import json

# Utility to generate event with duration
def create_event(event_type, day, start_hour, duration_hours=1):
    start_time = day + timedelta(hours=start_hour)
    end_time = start_time + timedelta(hours=duration_hours)
    return {
        "type": event_type,
        "start_time": start_time.isoformat(),
        "end_time": end_time.isoformat()
    }

# Simulate routine (morning/evening)
def simulate_routine(user, start_date, days=60):
    events = []
    for d in range(days):
        day = start_date + timedelta(days=d)
        if user["morning_person"]:
            events.append(create_event("routine", day, random.randint(6, 9)))
        events.append(create_event("routine", day, random.randint(18, 21)))
    return events

# Simulate Hawkes-like bursty communication
def simulate_communication(user, start_date, days=60, mu=0.2, alpha=0.8, beta=1.2):
    t = 0
    events = []
    while t < days:
        lambda_t = mu + sum([alpha * np.exp(-beta * (t - e)) for e in events])
        w = -np.log(np.random.rand()) / lambda_t
        t += w
        if t >= days:
            break
        e_day = start_date + timedelta(days=int(t))
        e_hour = random.randint(9, 22)
        events.append(t)
    return [create_event("communication", start_date + timedelta(days=int(t)), random.randint(9, 22)) for t in events]

# Rayleigh interest spikes
def simulate_interest_event(event_type, start_date, days=60, mu=1.0, sigma=3.0):
    t, current = [], 0
    while current < days:
        u = np.random.rand()
        delta = np.sqrt(-2 * sigma**2 * np.log(1 - u)) / mu
        current += delta
        if current < days:
            t.append(current)
    return [create_event(event_type, start_date + timedelta(days=int(ti)), random.randint(10, 22), duration_hours=2) for ti in t]

# Travel (decaying frequency)
def simulate_travel(user, start_date, days=60):
    travel_events = []
    freq = 6 if user["preferences"]["travel_freq"] == "low" else 2
    decay_factor = 0.9
    day = 0
    for i in range(freq):
        if day >= days:
            break
        travel_events.append(create_event("travel", start_date + timedelta(days=day), random.randint(5, 23), duration_hours=3))
        day += int(np.random.exponential(scale=10 * decay_factor))
        decay_factor *= 1.1  # Increase gaps
    return travel_events

# Education: stable, growing or decaying
def simulate_education(user, start_date, days=60):
    pattern = user["preferences"]["education_pattern"]
    events = []
    for d in range(days):
        if pattern == "growing" and d > days // 2:
            prob = 0.7
        elif pattern == "decaying" and d < days // 2:
            prob = 0.7
        else:
            prob = 0.3
        if np.random.rand() < prob:
            events.append(create_event("education", start_date + timedelta(days=d), random.randint(10, 20), duration_hours=2))
    return events

# Main simulation runner
def simulate_user_life(user, days=60):
    start_date = datetime.now()
    events = []

    events += simulate_routine(user, start_date, days)
    events += simulate_communication(user, start_date, days)
    events += simulate_interest_event("behavior", start_date, days)
    events += simulate_interest_event("interest", start_date, days)
    events += simulate_travel(user, start_date, days)
    events += simulate_education(user, start_date, days)

    return sorted(events, key=lambda x: x["start_time"])

# Run simulation
user = {
    "user_id": "u42",
    "morning_person": True,
    "interests": ["AI", "travel", "fitness"],
    "preferences": {
        "communication_style": "text",
        "travel_freq": "low",
        "education_pattern": "growing"
    }
}

events = simulate_user_life(user, days=60)

# Output first 10 events
for e in events[:10]:
    print(json.dumps(e, indent=2))

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from collections import defaultdict

# 1. Group events by type
def group_events_by_type(events):
    grouped = defaultdict(list)
    for event in events:
        start = datetime.fromisoformat(event["start_time"])
        end = datetime.fromisoformat(event["end_time"])
        grouped[event["type"]].append((start, end))
    return grouped

# 2. Plot function
def plot_life_events(events):
    grouped = group_events_by_type(events)
    fig, ax = plt.subplots(figsize=(12, 6))

    event_types = list(grouped.keys())
    colors = plt.cm.tab10.colors

    for i, event_type in enumerate(event_types):
        for (start, end) in grouped[event_type]:
            ax.plot([start, end], [i, i], color=colors[i % len(colors)], linewidth=3)

    # Format y-axis
    ax.set_yticks(range(len(event_types)))
    ax.set_yticklabels(event_types)
    ax.set_xlabel("Date")
    ax.set_title("User Life Events Timeline (Simulated)")

    # Format x-axis
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=5))
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    fig.autofmt_xdate()

    plt.tight_layout()
    plt.grid(True, axis='x', linestyle='--', alpha=0.3)
    plt.show()

# 3. Call the function
plot_life_events(events)

# decaying growing = ground truth
# check whether rayliegh , hawkes, temporal point process
# generate smartphone data
# Modular



# 1. modeling adaption
# 2. Evaluation (public datasets)
# users
# define growing and decaying

import numpy as np
from datetime import datetime, timedelta
import random
import json

# Utility to generate event with duration
def create_event(event_type, day, start_hour, duration_hours=1):
    start_time = day + timedelta(hours=start_hour)
    end_time = start_time + timedelta(hours=duration_hours)
    return {
        "type": event_type,
        "start_time": start_time.isoformat(),
        "end_time": end_time.isoformat()
    }

# Simulate routine (morning/evening)
def simulate_routine(user, start_date, days=60):
    events = []
    for d in range(days):
        day = start_date + timedelta(days=d)
        if user["morning_person"]:
            events.append(create_event("routine", day, random.randint(6, 9)))
        events.append(create_event("routine", day, random.randint(18, 21)))
    return events

# Simulate Hawkes-like bursty communication
def simulate_communication(user, start_date, days=60, mu=0.2, alpha=0.8, beta=1.2):
    t = 0
    events = []
    while t < days:
        lambda_t = mu + sum([alpha * np.exp(-beta * (t - e)) for e in events])
        w = -np.log(np.random.rand()) / lambda_t
        t += w
        if t >= days:
            break
        e_day = start_date + timedelta(days=int(t))
        e_hour = random.randint(9, 22)
        events.append(t)
    return [create_event("communication", start_date + timedelta(days=int(t)), random.randint(9, 22)) for t in events]

# Rayleigh interest spikes
def simulate_interest_event(event_type, start_date, days=60, mu=1.0, sigma=3.0):
    t, current = [], 0
    while current < days:
        u = np.random.rand()
        delta = np.sqrt(-2 * sigma**2 * np.log(1 - u)) / mu
        current += delta
        if current < days:
            t.append(current)
    return [create_event(event_type, start_date + timedelta(days=int(ti)), random.randint(10, 22), duration_hours=2) for ti in t]

# Travel (decaying frequency)
def simulate_travel(user, start_date, days=60):
    travel_events = []
    freq = 6 if user["preferences"]["travel_freq"] == "low" else 2
    decay_factor = 0.9
    day = 0
    for i in range(freq):
        if day >= days:
            break
        travel_events.append(create_event("travel", start_date + timedelta(days=day), random.randint(5, 23), duration_hours=3))
        day += int(np.random.exponential(scale=10 * decay_factor))
        decay_factor *= 1.1  # Increase gaps
    return travel_events

# Main simulation runner
def simulate_user_life(user, days=60):
    start_date = datetime.now()
    events = []

    events += simulate_routine(user, start_date, days)
    events += simulate_communication(user, start_date, days)
    events += simulate_interest_event("behavior", start_date, days)
    events += simulate_interest_event("interest", start_date, days)
    events += simulate_travel(user, start_date, days)

    return sorted(events, key=lambda x: x["start_time"])
events = simulate_user_life(user, days=60)