# -*- coding: utf-8 -*-
"""subgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSUnZuyPJzej5ePuE5IMYio4-bKMFWRR
"""

!pip install rdflib

import os
import re
from datetime import date, timedelta
from typing import List, Dict, Set

import networkx as nx
import numpy as np
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF

# Define the namespace from the TTL file for easier access
SDO = Namespace("http://www.example.org/smartphone-data-ontology#")

def extract_snapshot(g: Graph, day: date) -> Graph:
    """
    Extracts a snapshot of the TKG for a given day.
    NOTE: The provided TTL file has no timestamps. For this reason, we are treating
    the entire graph as a single snapshot for any given day in the range.
    This function can be modified to filter triples based on a timestamp predicate
    if your data includes it.
    """
    return g

def compute_node_embeddings(graph: nx.Graph, rdf_graph: Graph) -> Dict[URIRef, np.ndarray]:
    """
    Computes node embeddings based on node types and their immediate neighborhood.

    Args:
        graph (nx.Graph): The NetworkX graph representation.
        rdf_graph (Graph): The original rdflib graph to get type information.

    Returns:
        A dictionary mapping each node to its embedding vector.
    """
    print("  Computing node embeddings...")
    # Get all unique rdf:type values in the graph
    types = sorted(list(set(o for s, p, o in rdf_graph if p == RDF.type)))
    type_to_index = {t: i for i, t in enumerate(types)}
    embedding_dim = len(types)

    initial_embeddings = {}

    # Create initial one-hot encoded vectors for each node based on its type
    for node in graph.nodes():
        node_vector = np.zeros(embedding_dim)
        # Query rdflib graph for the type of the node
        node_types = list(rdf_graph.objects(subject=node, predicate=RDF.type))
        for t in node_types:
            if t in type_to_index:
                node_vector[type_to_index[t]] = 1
        initial_embeddings[node] = node_vector

    final_embeddings = {}
    # Aggregate embeddings from neighbors (1-hop message passing)
    for node in graph.nodes():
        neighbor_embeddings = [initial_embeddings[node]] # Include self
        for neighbor in graph.neighbors(node):
            if neighbor in initial_embeddings:
                neighbor_embeddings.append(initial_embeddings[neighbor])

        if neighbor_embeddings:
            final_embeddings[node] = np.mean(neighbor_embeddings, axis=0)
        else:
            final_embeddings[node] = initial_embeddings[node]

    print(f"  Embeddings computed for {len(final_embeddings)} nodes.")
    return final_embeddings

def cosine_similarity(vec1: np.ndarray, vec2: np.ndarray) -> float:
    """Calculates the cosine similarity between two vectors."""
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0.0
    return dot_product / (norm_vec1 * norm_vec2)

def extract_subgraph_with_embedding_filter(
    graph: nx.Graph,
    anchor_node: URIRef,
    embeddings: Dict[URIRef, np.ndarray],
    radius: int = 3,
    threshold: float = 0.5
) -> nx.Graph:
    """
    Extracts a subgraph by expanding from an anchor and filtering edges by embedding similarity.
    """
    if anchor_node not in graph:
        print(f"    Anchor node {anchor_node} not in graph.")
        return nx.Graph()

    # 1. Expand from the anchor to get a k-hop neighborhood
    ego_graph = nx.ego_graph(graph, anchor_node, radius=radius)

    # 2. Filter edges in the ego-graph based on embedding similarity
    filtered_subgraph = nx.Graph()
    for u, v in ego_graph.edges():
        if u in embeddings and v in embeddings:
            sim = cosine_similarity(embeddings[u], embeddings[v])
            if sim >= threshold:
                filtered_subgraph.add_edge(u, v, **graph.get_edge_data(u, v))

    # Ensure all nodes from kept edges are in the graph, even if they become isolates
    if filtered_subgraph.number_of_edges() > 0:
        for node in ego_graph.nodes():
             if node not in filtered_subgraph:
                 # Check if any neighbor connection was kept
                 if any(neighbor in filtered_subgraph for neighbor in graph.neighbors(node)):
                    filtered_subgraph.add_node(node)

    return filtered_subgraph


def process_tkg_for_user(
    tkg_file_path: str,
    user_id: int,
    start_date: date,
    end_date: date,
    daily_anchor_nodes: Dict[date, List[URIRef]],
    subgraph_radius: int = 3,
    similarity_threshold: float = 0.1
):
    """
    Processes a TKG for a specific user over a date range.
    """
    output_dir = f"user{user_id}_subgraphs"
    os.makedirs(output_dir, exist_ok=True)
    print(f"\n--- Processing User ID: {user_id} from {tkg_file_path} ---")
    print(f"Output directory: {output_dir}")

    # Load the main TKG
    tkg = Graph()
    tkg.parse(tkg_file_path, format="turtle")

    current_date = start_date
    while current_date <= end_date:
        print(f"Processing snapshot for {current_date}...")

        daily_snapshot_rdf = extract_snapshot(tkg, current_date)

        if not daily_snapshot_rdf:
            print(f"  No data in snapshot for {current_date}.")
            current_date += timedelta(days=1)
            continue

        daily_graph_nx = nx.Graph()
        for s, p, o in daily_snapshot_rdf:
            if isinstance(o, Literal): # Don't add literals as nodes
                continue
            daily_graph_nx.add_edge(s, o, label=p)

        # Compute embeddings for the entire daily graph
        embeddings = compute_node_embeddings(daily_graph_nx, daily_snapshot_rdf)

        anchors = daily_anchor_nodes.get(current_date, [])
        if not anchors:
            print(f"  No anchor nodes for {current_date}.")
            current_date += timedelta(days=1)
            continue

        for i, anchor in enumerate(anchors):
            print(f"  Extracting subgraph around anchor: {anchor}")
            activity_subgraph = extract_subgraph_with_embedding_filter(
                daily_graph_nx,
                anchor,
                embeddings,
                radius=subgraph_radius,
                threshold=similarity_threshold
            )

            if activity_subgraph.number_of_nodes() > 0:
                subgraph_filename = f"{current_date}_anchor_{i+1}.gml"
                subgraph_path = os.path.join(output_dir, subgraph_filename)
                nx.write_gml(activity_subgraph, subgraph_path)
                print(f"    Saved subgraph with {activity_subgraph.number_of_nodes()} nodes and {activity_subgraph.number_of_edges()} edges to {subgraph_path}")
            else:
                print(f"    No subgraph extracted for anchor {anchor} with the given parameters.")

        current_date += timedelta(days=1)

# --- Parameters for user_1.ttl ---
USER_ID = 1
TKG_FILE = "user_1.ttl"
START_DATE = date(2024, 1, 1) # Using a sample date
END_DATE = date(2024, 1, 1)   # Processing for one day as data is static

# --- Configuration ---
SUBGRAPH_HOPS = 3
# This threshold is crucial. Start with a low value (e.g., 0.01) to ensure you get results,
# then increase it to make the subgraphs more specific. A value of 1.0 means only nodes
# with identical types and neighborhoods will be connected.
SIMILARITY_THRESHOLD = 0.1

# Define anchor nodes for the specified date.
# These are example URIs taken from your user_1.ttl file.
DAILY_ANCHORS = {
    date(2024, 1, 1): [
        SDO["AppUsage_00021ae1-3a43-4c3d-9c07-2f83508dc148"],
        SDO["Location_0045494d-3529-5e41-a8b2-e7fb21a5f444"]
    ]
}

# Run the processing pipeline
process_tkg_for_user(
    tkg_file_path=TKG_FILE,
    user_id=USER_ID,
    start_date=START_DATE,
    end_date=END_DATE,
    daily_anchor_nodes=DAILY_ANCHORS,
    subgraph_radius=SUBGRAPH_HOPS,
    similarity_threshold=SIMILARITY_THRESHOLD
)

print("\n\nAll processing complete.")

import os
import re
from datetime import datetime
from typing import List, Dict, Tuple
import networkx as nx
import numpy as np

def group_subgraphs_by_activity(folder_path: str) -> Dict[str, List[Tuple[datetime, nx.Graph]]]:
    """
    Scans a directory for .gml files and groups them by anchor.
    Filenames are expected in the format 'YYYY-MM-DD_anchor_N.gml'.

    Args:
        folder_path: The path to the directory containing subgraph files.

    Returns:
        A dictionary where keys are anchor IDs (e.g., 'anchor_1') and
        values are lists of (timestamp, graph) tuples, sorted by timestamp.
    """
    if not os.path.isdir(folder_path):
        print(f"Error: Directory not found at '{folder_path}'")
        return {}

    activities = {}
    for filename in os.listdir(folder_path):
        if not filename.endswith(".gml"):
            continue

        # Regex to parse 'YYYY-MM-DD_anchor_N.gml'
        match = re.match(r"(\d{4}-\d{2}-\d{2})_(anchor_\d+)\.gml", filename)
        if not match:
            continue

        date_str, anchor_id = match.groups()
        try:
            timestamp = datetime.strptime(date_str, "%Y-%m-%d")
            graph_path = os.path.join(folder_path, filename)
            graph = nx.read_gml(graph_path, label='id') # Use 'id' if nodes are strings

            if anchor_id not in activities:
                activities[anchor_id] = []
            activities[anchor_id].append((timestamp, graph))

        except (ValueError, nx.NetworkXError) as e:
            print(f"Warning: Could not process file '{filename}'. Reason: {e}")
            continue

    # Sort each activity's graphs by date
    for anchor_id in activities:
        activities[anchor_id].sort(key=lambda x: x[0])

    return activities

def calculate_graph_similarity(g1: nx.Graph, g2: nx.Graph) -> Tuple[float, float]:
    """
    Calculates the Jaccard similarity for nodes and edges between two graphs.

    Returns:
        A tuple containing (node_jaccard_similarity, edge_jaccard_similarity).
    """
    nodes1 = set(g1.nodes())
    nodes2 = set(g2.nodes())

    # Create sets of edges (as sorted tuples to be canonical)
    edges1 = set(tuple(sorted(edge)) for edge in g1.edges())
    edges2 = set(tuple(sorted(edge)) for edge in g2.edges())

    node_intersection = len(nodes1.intersection(nodes2))
    node_union = len(nodes1.union(nodes2))
    node_jaccard = node_intersection / node_union if node_union > 0 else 0

    edge_intersection = len(edges1.intersection(edges2))
    edge_union = len(edges1.union(edges2))
    edge_jaccard = edge_intersection / edge_union if edge_union > 0 else 0

    return node_jaccard, edge_jaccard

def analyze_activity_trend(
    graphs: List[nx.Graph],
    growth_threshold: float = 0.15,
    decay_threshold: float = -0.15,
    stability_jaccard_threshold: float = 0.7
) -> str:
    """
    Analyzes a sequence of graphs to determine its trend.

    Args:
        graphs: A list of NetworkX graphs, sorted chronologically.
        growth_threshold: The average percentage increase in size to be considered 'Growing'.
        decay_threshold: The average percentage decrease in size to be considered 'Decaying'.
        stability_jaccard_threshold: The minimum Jaccard similarity to be considered 'Stable'.

    Returns:
        A string classification: 'Growing', 'Decaying', 'Stable', 'Volatile', or 'Insufficient Data'.
    """
    if len(graphs) < 2:
        return "Insufficient Data"

    size_changes = []
    jaccard_similarities = []

    for i in range(len(graphs) - 1):
        g1, g2 = graphs[i], graphs[i+1]

        # Calculate size change (using number of nodes as the primary metric)
        size1 = g1.number_of_nodes()
        size2 = g2.number_of_nodes()
        if size1 > 0:
            change = (size2 - size1) / size1
            size_changes.append(change)

        # Calculate structural similarity
        node_jaccard, edge_jaccard = calculate_graph_similarity(g1, g2)
        # We use node similarity as the primary structural metric
        jaccard_similarities.append(node_jaccard)

    if not size_changes: # Handle case where first graph is empty
        return "Insufficient Data"

    avg_size_change = np.mean(size_changes)
    avg_jaccard_sim = np.mean(jaccard_similarities)

    print(f"    Metrics: Avg. Size Change: {avg_size_change:.2%}, Avg. Jaccard Sim: {avg_jaccard_sim:.2f}")

    # Classify based on the metrics
    if avg_size_change > growth_threshold:
        return "Growing"
    elif avg_size_change < decay_threshold:
        return "Decaying"
    else:
        # Size is relatively constant, now check if the structure is also constant
        if avg_jaccard_sim >= stability_jaccard_threshold:
            return "Stable"
        else:
            return "Volatile (size is stable, but components are changing)"


if __name__ == '__main__':
    # --- Configuration ---
    # This should point to the output directory of the previous script
    SUBGRAPH_FOLDER = "user1_subgraphs"

    # --- Create dummy data for demonstration ---
    # This part simulates the output of the previous script for a multi-day scenario.
    print("--- Creating dummy subgraph files for demonstration ---")
    os.makedirs(SUBGRAPH_FOLDER, exist_ok=True)

    # Activity 1: Growing
    g1 = nx.path_graph(3)
    nx.write_gml(g1, os.path.join(SUBGRAPH_FOLDER, "2024-01-01_anchor_1.gml"))
    g2 = nx.path_graph(5)
    nx.write_gml(g2, os.path.join(SUBGRAPH_FOLDER, "2024-01-02_anchor_1.gml"))
    g3 = nx.star_graph(7)
    nx.write_gml(g3, os.path.join(SUBGRAPH_FOLDER, "2024-01-03_anchor_1.gml"))

    # Activity 2: Stable
    g4 = nx.cycle_graph(6)
    nx.write_gml(g4, os.path.join(SUBGRAPH_FOLDER, "2024-01-01_anchor_2.gml"))
    g5 = nx.cycle_graph(6) # Identical graph
    nx.relabel_nodes(g5, {0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f'}, copy=False) # Relabel to test Jaccard
    nx.write_gml(g5, os.path.join(SUBGRAPH_FOLDER, "2024-01-02_anchor_2.gml"))

    # Activity 3: Decaying
    g6 = nx.complete_graph(8)
    nx.write_gml(g6, os.path.join(SUBGRAPH_FOLDER, "2024-01-05_anchor_3.gml"))
    g7 = nx.complete_graph(5)
    nx.write_gml(g7, os.path.join(SUBGRAPH_FOLDER, "2024-01-06_anchor_3.gml"))

    # Activity 4: Insufficient Data
    g8 = nx.path_graph(4)
    nx.write_gml(g8, os.path.join(SUBGRAPH_FOLDER, "2024-01-10_anchor_4.gml"))
    print("--- Dummy files created ---\n")


    # --- Main Analysis ---
    print(f"--- Analyzing trends in '{SUBGRAPH_FOLDER}' ---")
    activities = group_subgraphs_by_activity(SUBGRAPH_FOLDER)

    if not activities:
        print("No activities found. Please ensure the folder contains valid .gml files.")
    else:
        for anchor_id, timed_graphs in activities.items():
            print(f"\nAnalyzing activity for '{anchor_id}'...")
            # Extract just the graphs from the (timestamp, graph) tuples
            graphs = [g for ts, g in timed_graphs]
            trend = analyze_activity_trend(graphs)
            print(f"  -> Trend Classification: {trend}")

    print("\n\nAnalysis complete.")



"""Evolution signatue"""

import os
import re
import shutil
from datetime import datetime, timedelta
from typing import List, Dict, Tuple

import networkx as nx
import numpy as np
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Define a consistent namespace
EX = Namespace("http://www.example.org/activity#")

def generate_dummy_subgraphs(base_dir: str, user_id: int) -> Dict[str, str]:
    """
    Generates a directory of dummy subgraph sequences in TTL format,
    each with a known ground truth trend.
    """
    output_dir = os.path.join(base_dir, f"user{user_id}_subgraphs_ttl")
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    print(f"--- Generating dummy data in '{output_dir}' ---")

    ground_truth = {
        "anchor_1": "Growing",
        "anchor_2": "Decaying",
        "anchor_3": "Stable",
        "anchor_4": "Volatile",
        "anchor_5": "Growing" # Another growing example
    }

    # --- Scenario 1: Growing Activity (anchor_1) ---
    for i in range(5): # 5 days of data
        g = Graph()
        g.bind("ex", EX)
        anchor = EX.anchor_1
        g.add((anchor, RDF.type, EX.Activity))
        for j in range(3 + i * 2): # Nodes increase over time
            node = EX[f"node_a1_{j}"]
            g.add((anchor, EX.hasParticipant, node))
            if j > 0:
                g.add((node, EX.interactsWith, EX[f"node_a1_{j-1}"]))
        date = datetime(2024, 1, 1) + timedelta(days=i)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_anchor_1.ttl"), format="turtle")

    # --- Scenario 2: Decaying Activity (anchor_2) ---
    for i in range(5):
        g = Graph()
        g.bind("ex", EX)
        anchor = EX.anchor_2
        g.add((anchor, RDF.type, EX.Activity))
        for j in range(10 - i * 2): # Nodes decrease over time
            node = EX[f"node_a2_{j}"]
            g.add((anchor, EX.relatedTo, node))
        date = datetime(2024, 1, 1) + timedelta(days=i)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_anchor_2.ttl"), format="turtle")

    # --- Scenario 3: Stable Activity (anchor_3) ---
    for i in range(5):
        g = Graph()
        g.bind("ex", EX)
        anchor = EX.anchor_3
        g.add((anchor, RDF.type, EX.Routine))
        for j in range(6): # Number of nodes is constant
            node = EX[f"person_{j}"]
            g.add((anchor, EX.involves, node))
        # Add a minor, insignificant change
        g.add((anchor, RDFS.comment, Literal(f"Day {i} report")))
        date = datetime(2024, 1, 1) + timedelta(days=i)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_anchor_3.ttl"), format="turtle")

    # --- Scenario 4: Volatile Activity (anchor_4) ---
    for i in range(5):
        g = Graph()
        g.bind("ex", EX)
        anchor = EX.anchor_4
        g.add((anchor, RDF.type, EX.SocialEvent))
        # Size is stable, but participants change
        for j in range(5):
            node = EX[f"guest_{i}_{j}"]
            g.add((anchor, EX.attendedBy, node))
        date = datetime(2024, 1, 1) + timedelta(days=i)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_anchor_4.ttl"), format="turtle")

    # --- Scenario 5: Another Growing Activity (anchor_5) ---
    for i in range(4):
        g = Graph()
        g.bind("ex", EX)
        anchor = EX.anchor_5
        g.add((anchor, RDF.type, EX.Project))
        for j in range(2 + i * 3):
            node = EX[f"task_{j}"]
            g.add((anchor, EX.hasTask, node))
        date = datetime(2024, 1, 10) + timedelta(days=i)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_anchor_5.ttl"), format="turtle")

    print("--- Dummy data generation complete ---\n")
    return ground_truth, output_dir


def group_subgraphs_by_activity(folder_path: str) -> Dict[str, List[Tuple[datetime, nx.Graph]]]:
    """
    Scans a directory for .ttl files and groups them by anchor, converting them to NetworkX graphs.
    """
    activities = {}
    for filename in sorted(os.listdir(folder_path)):
        if not filename.endswith(".ttl"):
            continue

        match = re.match(r"(\d{4}-\d{2}-\d{2})_(anchor_\d+)\.ttl", filename)
        if not match:
            continue

        date_str, anchor_id = match.groups()
        try:
            timestamp = datetime.strptime(date_str, "%Y-%m-%d")
            rdf_graph = Graph().parse(os.path.join(folder_path, filename), format="turtle")

            # Convert rdflib.Graph to networkx.Graph for analysis
            nx_graph = nx.Graph()
            for s, p, o in rdf_graph:
                if isinstance(o, Literal): continue # Literals are not nodes in the graph structure
                nx_graph.add_edge(s, o)

            if anchor_id not in activities:
                activities[anchor_id] = []
            activities[anchor_id].append((timestamp, nx_graph))

        except Exception as e:
            print(f"Warning: Could not process file '{filename}'. Reason: {e}")
            continue

    return activities

def calculate_graph_similarity(g1: nx.Graph, g2: nx.Graph) -> Tuple[float, float]:
    """Calculates the Jaccard similarity for nodes and edges between two graphs."""
    nodes1, nodes2 = set(g1.nodes()), set(g2.nodes())
    edges1 = set(tuple(sorted(e)) for e in g1.edges())
    edges2 = set(tuple(sorted(e)) for e in g2.edges())

    node_union = len(nodes1.union(nodes2))
    node_jaccard = len(nodes1.intersection(nodes2)) / node_union if node_union > 0 else 0

    edge_union = len(edges1.union(edges2))
    edge_jaccard = len(edges1.intersection(edges2)) / edge_union if edge_union > 0 else 0

    return node_jaccard, edge_jaccard

def analyze_activity_trend(graphs: List[nx.Graph], **kwargs) -> str:
    """Analyzes a sequence of graphs to determine its trend."""
    # Tunable parameters
    growth_threshold = kwargs.get('growth_threshold', 0.15)
    decay_threshold = kwargs.get('decay_threshold', -0.15)
    stability_jaccard_threshold = kwargs.get('stability_jaccard_threshold', 0.7)

    if len(graphs) < 2:
        return "Insufficient Data"

    size_changes, jaccard_similarities = [], []
    for i in range(len(graphs) - 1):
        g1, g2 = graphs[i], graphs[i+1]
        size1, size2 = g1.number_of_nodes(), g2.number_of_nodes()
        if size1 > 0:
            size_changes.append((size2 - size1) / size1)
        node_jaccard, _ = calculate_graph_similarity(g1, g2)
        jaccard_similarities.append(node_jaccard)

    if not size_changes: return "Insufficient Data"

    avg_size_change = np.mean(size_changes)
    avg_jaccard_sim = np.mean(jaccard_similarities)

    print(f"    Metrics: Avg. Size Change: {avg_size_change:.2%}, Avg. Jaccard Sim: {avg_jaccard_sim:.2f}")

    if avg_size_change > growth_threshold: return "Growing"
    if avg_size_change < decay_threshold: return "Decaying"
    if avg_jaccard_sim >= stability_jaccard_threshold: return "Stable"
    return "Volatile"

def evaluate_performance(y_true: List[str], y_pred: List[str], labels: List[str]):
    """Calculates and prints performance metrics."""
    print("\n\n--- Performance Evaluation ---")
    print(classification_report(y_true, y_pred, labels=labels))

    # Display Confusion Matrix
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(cmap=plt.cm.Blues)
    plt.title("Trend Analysis Confusion Matrix")
    plt.show()


if __name__ == '__main__':
    # 1. Generate a dummy dataset with known ground truth
    ground_truth, data_folder = generate_dummy_subgraphs(base_dir="dummy_data", user_id=1)

    # 2. Group the generated .ttl files by activity
    activities = group_subgraphs_by_activity(data_folder)

    # 3. Analyze trends and store predictions
    print("--- Analyzing Activity Trends ---")
    predictions = {}
    if not activities:
        print("No activities found to analyze.")
    else:
        for anchor_id, timed_graphs in activities.items():
            print(f"\nAnalyzing activity for '{anchor_id}' (Ground Truth: {ground_truth.get(anchor_id, 'N/A')})...")
            graphs = [g for ts, g in timed_graphs]
            trend = analyze_activity_trend(graphs)
            predictions[anchor_id] = trend
            print(f"  -> Trend Prediction: {trend}")

    # 4. Evaluate Performance
    # Align ground truth and predictions for comparison
    labels = sorted(list(set(ground_truth.values())))
    y_true = []
    y_pred = []

    # Ensure we only evaluate anchors that are in both lists
    for anchor_id in sorted(ground_truth.keys()):
        if anchor_id in predictions:
            y_true.append(ground_truth[anchor_id])
            y_pred.append(predictions[anchor_id])

    if y_true:
        evaluate_performance(y_true, y_pred, labels=labels)
    else:
        print("\nCould not perform evaluation. No matching predictions found for ground truth.")

!pip install node2vec

import os
import re
import shutil
from datetime import datetime, timedelta
from typing import List, Dict, Tuple

# --- Installation Note ---
# You will need to install the following libraries for this script to run:
# pip install rdflib networkx numpy scikit-learn matplotlib node2vec

import networkx as nx
import numpy as np
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from scipy.stats import linregress
from node2vec import Node2Vec

# Define a consistent namespace
SDO = Namespace("http://www.example.org/smartphone-data-ontology#")

# ---
# STAGE 1: REALISTIC DATA GENERATION
# ---

def generate_realistic_subgraphs(base_dir: str, user_id: int) -> Tuple[Dict[str, str], str]:
    """Generates a directory of more realistic subgraph sequences in TTL format."""
    output_dir = os.path.join(base_dir, f"user{user_id}_subgraphs_realistic")
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    print(f"--- Generating realistic dummy data in '{output_dir}' ---")

    ground_truth = {
        "anchor_1": "Growing", "anchor_2": "Decaying", "anchor_3": "Stable",
        "anchor_4": "Volatile", "anchor_5": "Shifting"
    }

    def save_graph(g, anchor_name, day_index):
        date = datetime(2024, 1, 1) + timedelta(days=day_index)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_{anchor_name}.ttl"), format="turtle")

    # Scenario 1: Growing (New Project)
    for i in range(8):
        g = Graph()
        g.bind("sdo", SDO)
        num_nodes = 2 + int(i**1.5)
        for j in range(num_nodes): g.add((SDO.anchor_1, SDO.hasTask, SDO[f"task_a1_{j}"]))
        save_graph(g, "anchor_1", i)

    # Scenario 2: Decaying (Fading Hobby)
    for i in range(8):
        g = Graph()
        g.bind("sdo", SDO)
        num_nodes = 15 - i * 2
        if i == 4: num_nodes += 3
        for j in range(max(0, num_nodes)): g.add((SDO.anchor_2, SDO.generatesUsage, SDO[f"usage_a2_{j}"]))
        save_graph(g, "anchor_2", i)

    # Scenario 3: Stable (Work Routine)
    for i in range(8):
        g = Graph()
        g.bind("sdo", SDO)
        for j in range(5): g.add((SDO.anchor_3, SDO.hasColleague, SDO[f"colleague_{j}"]))
        g.add((SDO.anchor_3, SDO.hasMeeting, SDO[f"meeting_{i}"]))
        save_graph(g, "anchor_3", i)

    # Scenario 4: Volatile (Socializing)
    for i in range(8):
        g = Graph()
        g.bind("sdo", SDO)
        group_id = i % 3
        for j in range(4): g.add((SDO.anchor_4, SDO.withContact, SDO[f"friend_group_{group_id}_{j}"]))
        save_graph(g, "anchor_4", i)

    # Scenario 5: Shifting (Research -> Development)
    for i in range(8):
        g = Graph()
        g.bind("sdo", SDO)
        if i < 4:
            for j in range(5): g.add((SDO.anchor_5, SDO.readsPaper, SDO[f"paper_{j}_{i}"]))
        else:
            for j in range(6): g.add((SDO.anchor_5, SDO.writesCode, SDO[f"module_{j}"]))
        save_graph(g, "anchor_5", i)

    print("--- Realistic data generation complete ---\n")
    return ground_truth, output_dir

# ---
# STAGE 2: ANALYSIS STRATEGIES
# ---

class TrendAnalysisStrategy:
    """Base class for a trend analysis strategy."""
    def __init__(self, name: str):
        self.name = name

    def analyze(self, graphs: List[nx.Graph]) -> str:
        raise NotImplementedError

    def _load_graphs(self, folder_path: str) -> Dict[str, List[nx.Graph]]:
        activities = {}
        if not os.path.isdir(folder_path): return {}
        for filename in sorted(os.listdir(folder_path)):
            if not filename.endswith(".ttl"): continue
            match = re.match(r"(\d{4}-\d{2}-\d{2})_(anchor_\d+)\.ttl", filename)
            if not match: continue
            _, anchor_id = match.groups()
            rdf_graph = Graph().parse(os.path.join(folder_path, filename), format="turtle")
            nx_graph = nx.Graph()
            for s, p, o in rdf_graph:
                if not isinstance(o, Literal): nx_graph.add_edge(s, o)
            if anchor_id not in activities: activities[anchor_id] = []
            activities[anchor_id].append(nx_graph)
        return activities

# --- APPROACH 1: Jaccard + Size Analysis (Baseline) ---
class StrategyJaccardSize(TrendAnalysisStrategy):
    def __init__(self):
        super().__init__("Jaccard + Size")

    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"
        size_changes, jaccard_sims = [], []
        for g1, g2 in zip(graphs, graphs[1:]):
            s1, s2 = g1.number_of_nodes(), g2.number_of_nodes()
            if s1 > 0: size_changes.append((s2 - s1) / s1)
            n1, n2 = set(g1.nodes()), set(g2.nodes())
            union = len(n1.union(n2))
            jaccard_sims.append(len(n1.intersection(n2)) / union if union > 0 else 0)

        if not size_changes: return "Insufficient Data"
        avg_size_change, avg_jaccard = np.mean(size_changes), np.mean(jaccard_sims)

        if avg_size_change > 0.15: return "Growing"
        if avg_size_change < -0.15: return "Decaying"
        if avg_jaccard > 0.7: return "Stable"
        if avg_jaccard < 0.2: return "Shifting"
        return "Volatile"

# --- APPROACH 2: Time Series on Graph Metrics ---
class StrategyTimeSeriesMetrics(TrendAnalysisStrategy):
    def __init__(self):
        super().__init__("Time Series on Graph Metrics")

    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 3: return "Insufficient Data"
        nodes = [g.number_of_nodes() for g in graphs]
        time_steps = list(range(len(graphs)))
        node_slope, _, r_val, _, _ = linregress(time_steps, nodes)
        mean_nodes = np.mean(nodes)
        norm_slope = node_slope / mean_nodes if mean_nodes > 0 else 0

        if r_val**2 > 0.6: # Strong linear trend
            if norm_slope > 0.05: return "Growing"
            if norm_slope < -0.05: return "Decaying"

        node_variance = np.std(nodes) / mean_nodes if mean_nodes > 0 else 0
        if node_variance < 0.1: return "Stable"
        if node_variance > 0.4: return "Volatile"
        return "Shifting"

# --- APPROACH 3: Graph Feature Trajectory (FIXED) ---
class StrategyGraphFeature(TrendAnalysisStrategy):
    def __init__(self):
        super().__init__("Graph Feature Trajectory")

    def _get_feature_vectors(self, graphs: List[nx.Graph]) -> List[np.ndarray]:
        # FIX: Create a consistent vocabulary of nodes for the entire sequence
        vocab = sorted(list(set(node for g in graphs for node in g.nodes())))
        node_to_idx = {node: i for i, node in enumerate(vocab)}

        vectors = []
        for g in graphs:
            vec = np.zeros(len(vocab))
            for node in g.nodes():
                if node in node_to_idx:
                    vec[node_to_idx[node]] = g.degree(node)
            norm = np.linalg.norm(vec)
            vectors.append(vec / norm if norm > 0 else vec)
        return vectors

    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"
        embeddings = self._get_feature_vectors(graphs)
        distances = [np.linalg.norm(e1 - e2) for e1, e2 in zip(embeddings, embeddings[1:])]
        avg_dist = np.mean(distances)

        if avg_dist < 0.2: return "Stable"
        if avg_dist > 0.9: return "Shifting" # Large distance means structure is fundamentally different

        # Check size trend if not clearly stable or shifting
        nodes = [g.number_of_nodes() for g in graphs]
        slope, _, _, _, _ = linregress(list(range(len(graphs))), nodes)
        norm_slope = slope / np.mean(nodes) if np.mean(nodes) > 0 else 0
        if norm_slope > 0.05: return "Growing"
        if norm_slope < -0.05: return "Decaying"
        return "Volatile"

# --- APPROACH 4: Node2Vec + Aggregation ---
class StrategyNode2Vec(TrendAnalysisStrategy):
    def __init__(self, dimensions=16, walk_length=10, num_walks=50):
        super().__init__("Node2Vec Embedding")
        self.dimensions = dimensions
        self.walk_length = walk_length
        self.num_walks = num_walks

    def _get_graph_embedding(self, graph: nx.Graph) -> np.ndarray:
        if graph.number_of_nodes() == 0:
            return np.zeros(self.dimensions)

        # Node2Vec conversion
        n2v = Node2Vec(graph, dimensions=self.dimensions, walk_length=self.walk_length,
                       num_walks=self.num_walks, workers=4, quiet=True)
        model = n2v.fit(window=5, min_count=1, batch_words=4)

        # Aggregate node vectors (mean) to get a graph vector
        node_vectors = [model.wv[str(node)] for node in graph.nodes()]
        if not node_vectors:
            return np.zeros(self.dimensions)
        return np.mean(node_vectors, axis=0)

    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"

        embeddings = [self._get_graph_embedding(g) for g in graphs]

        # Same trajectory analysis as Approach 3, but on more powerful embeddings
        distances = [np.linalg.norm(e1 - e2) for e1, e2 in zip(embeddings, embeddings[1:])]
        avg_dist = np.mean(distances)

        if avg_dist < 0.1: return "Stable"
        if avg_dist > 0.5: return "Shifting"

        nodes = [g.number_of_nodes() for g in graphs]
        slope, _, _, _, _ = linregress(list(range(len(graphs))), nodes)
        norm_slope = slope / np.mean(nodes) if np.mean(nodes) > 0 else 0
        if norm_slope > 0.05: return "Growing"
        if norm_slope < -0.05: return "Decaying"
        return "Volatile"

# ---
# STAGE 3: PERFORMANCE EVALUATION
# ---

def evaluate_performance(strategy_name: str, y_true: List[str], y_pred: List[str], labels: List[str]):
    print(f"\n--- Performance Evaluation for: {strategy_name} ---")
    present_labels = sorted(list(set(y_true) | set(y_pred)))
    print(classification_report(y_true, y_pred, labels=present_labels, zero_division=0))

    cm = confusion_matrix(y_true, y_pred, labels=present_labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=present_labels)
    fig, ax = plt.subplots(figsize=(8, 6))
    disp.plot(cmap=plt.cm.Blues, ax=ax, xticks_rotation='vertical')
    plt.title(f"Confusion Matrix for {strategy_name}")
    plt.tight_layout()
    plt.show()

if __name__ == '__main__':
    ground_truth, data_folder = generate_realistic_subgraphs(base_dir="dummy_data_realistic", user_id=1)

    strategies = [
        StrategyJaccardSize(),
        StrategyTimeSeriesMetrics(),
        StrategyGraphFeature(),
        StrategyNode2Vec()
    ]

    all_labels = sorted(list(set(ground_truth.values())))

    for strategy in strategies:
        activity_graphs = strategy._load_graphs(data_folder)
        predictions = {}
        print(f"\n--- Running analysis with: {strategy.name} ---")
        for anchor_id, graphs in activity_graphs.items():
            if anchor_id in ground_truth:
                print(f"  Analyzing '{anchor_id}'...")
                predictions[anchor_id] = strategy.analyze(graphs)

        y_true, y_pred = [], []
        for anchor_id, true_label in ground_truth.items():
            if anchor_id in predictions:
                y_true.append(true_label)
                y_pred.append(predictions[anchor_id])

        if y_true:
            evaluate_performance(strategy.name, y_true, y_pred, labels=all_labels)
        else:
            print(f"Could not run evaluation for {strategy.name}.")

!pip install torch torch_geometric numpy scikit-learn matplotlib
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html

import torch
import torch.nn as nn
import numpy as np
from math import sin, cos, pi
import random
import os

# Attempt to import PyTorch Geometric
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv
except ImportError:
    print("PyTorch Geometric not found. Please install it via: pip install torch_geometric")
    # In a real application, you'd want to handle this more gracefully
    # or ensure the dependency is met.
    # exit()

# --- 1. Configuration Constants ---
# These should match the configuration used during model training.
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Model Configs
T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM = 5, 64, 16
T_MAX_SEQ_LEN = 150
G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS = 64, 32, 2
NODE_FEATURE_DIM = 32

# Graph Structure Metadata
NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log')
]

# --- 2. Model Architecture Definitions ---
# These classes define the neural network architectures. They must be
# identical to the ones used for training the models you are loading.

class TemporalSpreadVGAE(nn.Module):
    """
    Temporal Variational Graph Autoencoder for time-series data.
    Encodes a sequence of events into a latent vector.
    """
    def __init__(self, input_dim, hidden_dim, latent_dim, output_dim, num_layers=2):
        super().__init__()
        self.encoder_rnn = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)
        self.fc_mu = nn.Linear(hidden_dim * 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim * 2, latent_dim)
        # Decoder is not needed for embedding generation, but included for completeness
        self.decoder_fc = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
            nn.Softmax(dim=-1)
        )

    def encode(self, x):
        _, (h, _) = self.encoder_rnn(x)
        # Concatenate the final hidden states from both directions
        h_concat = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1)
        mu = self.fc_mu(h_concat)
        logvar = self.fc_logvar(h_concat)
        return mu, logvar

    def forward(self, x):
        # For inference, we only need the encoding part.
        mu, _ = self.encode(x)
        return mu

class DSENVGAE(nn.Module):
    """
    Dynamic Social Entity Network VGAE for heterogeneous graphs.
    Encodes a graph's structure and node features into a latent vector
    and produces embeddings for each node.
    """
    def __init__(self, node_feat_dim, embed_dim, latent_dim, num_han_layers, metadata):
        super().__init__()
        self.latent_dim = latent_dim
        self.metadata = metadata

        # Linear projection for each node type
        self.lin_dict = nn.ModuleDict({
            nt: nn.Linear(node_feat_dim, embed_dim) for nt in metadata[0]
        })

        # Heterogeneous Graph Attention Layers
        self.han_convs = nn.ModuleList([
            HANConv(embed_dim, embed_dim, metadata=metadata, heads=4) for _ in range(num_han_layers)
        ])

        # Output layers for graph-level embedding
        self.mu_linear = nn.Linear(embed_dim, latent_dim)
        self.logvar_linear = nn.Linear(embed_dim, latent_dim)

    def encode(self, data):
        # Project node features into a common embedding space
        x_dict = {nt: self.lin_dict[nt](x) for nt, x in data.x_dict.items()}

        # Process through HAN layers
        for conv in self.han_convs:
            x_dict = conv(x_dict, data.edge_index_dict)

        # Pool node embeddings to get a graph-level representation
        # We only pool from node types that actually have nodes in the graph
        pooled_embs = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]

        if pooled_embs:
            graph_level_emb = torch.stack(pooled_embs).mean(dim=0)
        else:
            # Handle empty graphs
            graph_level_emb = torch.zeros(self.mu_linear.in_features, device=next(self.parameters()).device)

        mu = self.mu_linear(graph_level_emb)
        logvar = self.logvar_linear(graph_level_emb)

        # Return graph-level latent variables and node-level embeddings
        return mu, logvar, x_dict

    def forward(self, data):
        # For inference, we only need the encoding part.
        mu, _, node_embeddings = self.encode(data)
        return mu, node_embeddings


# --- 3. Reusable Embedding Generator Class ---

class EmbeddingGenerator:
    """
    A class to load pre-trained models and generate temporal, graph,
    and node embeddings for new, unseen daily data.
    """
    def __init__(self, temporal_model_path, graph_model_path, device=DEVICE):
        """
        Initializes the generator by loading pre-trained model weights.

        Args:
            temporal_model_path (str): Path to the .pth file for the temporal model.
            graph_model_path (str): Path to the .pth file for the graph model.
            device (torch.device): The device to run the models on (e.g., 'cpu' or 'cuda').
        """
        self.device = device
        print(f"Initializing EmbeddingGenerator on device: {self.device}")

        # Initialize model architectures
        # Note: The output_dim for the temporal decoder isn't used for inference,
        # so we can set it to a placeholder value like 24.
        self.temporal_model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24).to(self.device)
        self.graph_model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES)).to(self.device)

        # Load pre-trained weights
        self.temporal_model.load_state_dict(torch.load(temporal_model_path, map_location=self.device))
        self.graph_model.load_state_dict(torch.load(graph_model_path, map_location=self.device))

        # Set models to evaluation mode
        self.temporal_model.eval()
        self.graph_model.eval()

        print("Models loaded and set to evaluation mode successfully.")

    def _preprocess_temporal_data(self, timestamps):
        """
        Converts a list of timestamps (in minutes) into a feature tensor.
        """
        features = []
        prev_time = 0
        # Sort timestamps to ensure correct time difference calculation
        sorted_ts = sorted(timestamps)

        for t in sorted_ts:
            h, m = t // 60, t % 60
            # Features: sin/cos of hour, sin/cos of minute, normalized time delta
            features.append([
                sin(2 * pi * h / 24), cos(2 * pi * h / 24),
                sin(2 * pi * m / 60), cos(2 * pi * m / 60),
                (t - prev_time) / 1440.0
            ])
            prev_time = t

        # Pad the sequence to the maximum length
        padding_needed = T_MAX_SEQ_LEN - len(features)
        if padding_needed > 0:
            features.extend([[0.0] * T_INPUT_DIM for _ in range(padding_needed)])

        # Truncate if longer than max length
        features = features[:T_MAX_SEQ_LEN]

        return torch.tensor(features, dtype=torch.float32).unsqueeze(0) # Add batch dimension

    def _finalize_graph(self, graph_data):
        """
        Ensures a HeteroData object has all required node and edge types defined,
        even if they are empty, to prevent errors in the graph model.
        """
        for n_type in NODE_TYPES:
            if n_type not in graph_data.node_types:
                # Add an empty tensor with the correct feature dimension
                graph_data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)

        for e_type in EDGE_TYPES:
            if e_type not in graph_data.edge_types:
                # Add an empty edge index tensor
                graph_data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)
        return graph_data

    @torch.no_grad()
    def get_embeddings(self, timestamps, graph_data):
        """
        Computes all embeddings for a given set of timestamps and a graph.

        Args:
            timestamps (list[int]): A list of event timestamps in minutes from midnight (e.g., [540, 555, 720]).
            graph_data (torch_geometric.data.HeteroData): The graph for the day.

        Returns:
            dict: A dictionary containing the following embeddings:
                  - 'temporal_embedding': (np.array)
                  - 'graph_embedding': (np.array)
                  - 'aggregate_embedding': (np.array)
                  - 'node_embeddings': (dict of np.array)
        """
        # 1. Preprocess and get temporal embedding
        temporal_input = self._preprocess_temporal_data(timestamps).to(self.device)
        temporal_mu, _ = self.temporal_model.encode(temporal_input)

        # 2. Preprocess and get graph and node embeddings
        finalized_graph = self._finalize_graph(graph_data).to(self.device)
        graph_mu, _, node_embs_dict = self.graph_model.encode(finalized_graph)

        # FIX: The temporal model outputs a 2D tensor [1, latent_dim] while the
        # graph model outputs a 1D tensor [latent_dim]. We add a batch dimension
        # to the graph embedding to make them compatible for concatenation.
        if graph_mu.dim() == 1:
            graph_mu = graph_mu.unsqueeze(0)

        # 3. Combine graph and temporal embeddings
        aggregate_emb = torch.cat([temporal_mu, graph_mu], dim=1)

        # 4. Convert all tensors to numpy arrays for easy use
        results = {
            "temporal_embedding": temporal_mu.cpu().numpy().flatten(),
            "graph_embedding": graph_mu.cpu().numpy().flatten(),
            "aggregate_embedding": aggregate_emb.cpu().numpy().flatten(),
            "node_embeddings": {nt: emb.cpu().numpy() for nt, emb in node_embs_dict.items()}
        }

        return results


# --- 4. Demonstration of Usage ---

def create_dummy_trained_models():
    """
    Creates and saves dummy model weights. In a real scenario, you would
    use your actual, trained model files.
    """
    print("\n--- Creating dummy pre-trained models for demonstration ---")
    # Create instances of the models
    temp_model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24)
    graph_model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES))

    # Save their initial (random) weights
    os.makedirs("dummy_models", exist_ok=True)
    torch.save(temp_model.state_dict(), "dummy_models/temporal_model.pth")
    torch.save(graph_model.state_dict(), "dummy_models/graph_model.pth")
    print("Dummy models saved to 'dummy_models/' directory.")


# if __name__ == '__main__':
#     # Step 1: Create dummy model weights for this example.
#     # You would skip this step if you already have trained models.
#     create_dummy_trained_models()

#     # Step 2: Instantiate the generator with the paths to the model weights.
#     try:
#         embedding_generator = EmbeddingGenerator(
#             temporal_model_path="dummy_models/temporal_model.pth",
#             graph_model_path="dummy_models/graph_model.pth"
#         )
#     except FileNotFoundError:
#         print("\nError: Model files not found. Please ensure the paths are correct.")
#         exit()

#     # Step 3: Create new, unseen data for which to generate embeddings.
#     # This simulates a new "day" of data you want to analyze.
#     print("\n--- Simulating a new, unseen day's data ---")

#     # Sample timestamps for a "work day"
#     new_day_timestamps = [t for t in np.random.normal(loc=570, scale=60, size=40)] # Morning work
#     new_day_timestamps.extend(np.random.normal(loc=900, scale=60, size=40)) # Afternoon work
#     new_day_timestamps = [int(t) for t in np.clip(new_day_timestamps, 0, 1439)]

#     # Sample graph for a "work day" with two people in an office
#     new_day_graph = HeteroData()
#     new_day_graph['person'].x = torch.randn(2, NODE_FEATURE_DIM) # Two people
#     new_day_graph['scene'].x = torch.randn(1, NODE_FEATURE_DIM)  # One scene (office)
#     # Both people appear in the scene
#     new_day_graph['person', 'appears_in', 'scene'].edge_index = torch.tensor([[0, 1], [0, 0]], dtype=torch.long)
#     # The two people interact
#     new_day_graph['person', 'interacts_with', 'person'].edge_index = torch.tensor([[0], [1]], dtype=torch.long)

#     print(f"Generated a sample day with {len(new_day_timestamps)} events and a graph with {new_day_graph.num_nodes} nodes.")

#     # Step 4: Use the generator to get the embeddings.
#     print("\n--- Computing embeddings for the new data ---")
#     embeddings = embedding_generator.get_embeddings(new_day_timestamps, new_day_graph)

#     # Step 5: Print the results to inspect them.
#     print("\n--- RESULTS ---")
#     print(f"Temporal Embedding Shape: {embeddings['temporal_embedding'].shape}")
#     print(f"Graph Embedding Shape:    {embeddings['graph_embedding'].shape}")
#     print(f"Aggregate Embedding Shape:  {embeddings['aggregate_embedding'].shape}")
#     print("\nNode Embeddings:")
#     for node_type, node_embs in embeddings['node_embeddings'].items():
#         print(f"  - Type '{node_type}': {node_embs.shape[0]} nodes, Embedding Shape: {node_embs.shape}")

import os
import re
import shutil
from datetime import datetime, timedelta
from typing import List, Dict, Tuple

# --- Installation Note ---
# You will need to install the following libraries for this script to run:
# pip install torch numpy scikit-learn matplotlib node2vec
# pip install torch_geometric
# Ensure you have a C++ compiler for PyTorch Geometric installation if needed.

import torch
import torch.nn as nn
import numpy as np
from math import sin, cos, pi

import networkx as nx
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from scipy.stats import linregress
from node2vec import Node2Vec

# Attempt to import PyTorch Geometric
try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HANConv
except ImportError:
    print("PyTorch Geometric not found. Please install it via: pip install torch_geometric")
    exit()


# ======================================================================================
# SECTION 1: USER-PROVIDED MODEL ARCHITECTURES AND EMBEDDING GENERATOR
# This section contains the code you provided for your pre-trained models.
# ======================================================================================

# --- 1.1. Configuration Constants ---
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM = 5, 64, 16
T_MAX_SEQ_LEN = 150
G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS = 64, 32, 2
NODE_FEATURE_DIM = 32
NODE_TYPES = ['person', 'scene', 'activity_log']
EDGE_TYPES = [
    ('person', 'interacts_with', 'person'),
    ('person', 'appears_in', 'scene'),
    ('person', 'performs', 'activity_log')
]

# --- 1.2. Model Architecture Definitions ---
class TemporalSpreadVGAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, output_dim, num_layers=2):
        super().__init__()
        self.encoder_rnn = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)
        self.fc_mu = nn.Linear(hidden_dim * 2, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim * 2, latent_dim)
    def encode(self, x):
        _, (h, _) = self.encoder_rnn(x)
        h_concat = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1)
        return self.fc_mu(h_concat), self.fc_logvar(h_concat)
    def forward(self, x):
        mu, _ = self.encode(x)
        return mu

class DSENVGAE(nn.Module):
    def __init__(self, node_feat_dim, embed_dim, latent_dim, num_han_layers, metadata):
        super().__init__()
        self.lin_dict = nn.ModuleDict({nt: nn.Linear(node_feat_dim, embed_dim) for nt in metadata[0]})
        self.han_convs = nn.ModuleList([HANConv(embed_dim, embed_dim, metadata=metadata, heads=4) for _ in range(num_han_layers)])
        self.mu_linear = nn.Linear(embed_dim, latent_dim)
        self.logvar_linear = nn.Linear(embed_dim, latent_dim)
    def encode(self, data):
        x_dict = {nt: self.lin_dict[nt](x) for nt, x in data.x_dict.items()}
        for conv in self.han_convs:
            x_dict = conv(x_dict, data.edge_index_dict)
        pooled_embs = [x.mean(dim=0) for x in x_dict.values() if x.size(0) > 0]
        graph_level_emb = torch.stack(pooled_embs).mean(dim=0) if pooled_embs else torch.zeros(self.mu_linear.in_features, device=next(self.parameters()).device)
        return self.mu_linear(graph_level_emb), self.logvar_linear(graph_level_emb), x_dict
    def forward(self, data):
        mu, _, node_embeddings = self.encode(data)
        return mu, node_embeddings

# --- 1.3. Reusable Embedding Generator Class ---
class EmbeddingGenerator:
    def __init__(self, temporal_model_path, graph_model_path, device=DEVICE):
        self.device = device
        self.temporal_model = TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24).to(self.device)
        self.graph_model = DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES)).to(self.device)
        self.temporal_model.load_state_dict(torch.load(temporal_model_path, map_location=self.device))
        self.graph_model.load_state_dict(torch.load(graph_model_path, map_location=self.device))
        self.temporal_model.eval()
        self.graph_model.eval()
    def _preprocess_temporal_data(self, timestamps):
        features = []
        prev_time = 0
        for t in sorted(timestamps):
            h, m = t // 60, t % 60
            features.append([sin(2 * pi * h / 24), cos(2 * pi * h / 24), sin(2 * pi * m / 60), cos(2 * pi * m / 60), (t - prev_time) / 1440.0])
            prev_time = t
        padding_needed = T_MAX_SEQ_LEN - len(features)
        if padding_needed > 0: features.extend([[0.0] * T_INPUT_DIM for _ in range(padding_needed)])
        return torch.tensor(features[:T_MAX_SEQ_LEN], dtype=torch.float32).unsqueeze(0)
    def _finalize_graph(self, graph_data):
        for n_type in NODE_TYPES:
            if n_type not in graph_data.node_types: graph_data[n_type].x = torch.empty((0, NODE_FEATURE_DIM), dtype=torch.float)
        for e_type in EDGE_TYPES:
            if e_type not in graph_data.edge_types: graph_data[e_type].edge_index = torch.empty((2, 0), dtype=torch.long)
        return graph_data
    @torch.no_grad()
    def get_embeddings(self, timestamps, graph_data):
        temporal_input = self._preprocess_temporal_data(timestamps).to(self.device)
        temporal_mu, _ = self.temporal_model.encode(temporal_input)
        finalized_graph = self._finalize_graph(graph_data).to(self.device)
        graph_mu, _, node_embs_dict = self.graph_model.encode(finalized_graph)
        if graph_mu.dim() == 1: graph_mu = graph_mu.unsqueeze(0)
        aggregate_emb = torch.cat([temporal_mu, graph_mu], dim=1)
        return {"graph_embedding": graph_mu.cpu().numpy().flatten()}

# --- 1.4. Dummy Model Creation ---
def create_dummy_trained_models():
    print("\n--- Creating dummy pre-trained models for demonstration ---")
    os.makedirs("dummy_models", exist_ok=True)
    torch.save(TemporalSpreadVGAE(T_INPUT_DIM, T_HIDDEN_DIM, T_LATENT_DIM, 24).state_dict(), "dummy_models/temporal_model.pth")
    torch.save(DSENVGAE(NODE_FEATURE_DIM, G_EMBEDDING_DIM, G_LATENT_DIM, G_NUM_HAN_LAYERS, (NODE_TYPES, EDGE_TYPES)).state_dict(), "dummy_models/graph_model.pth")
    print("Dummy models saved to 'dummy_models/' directory.")


# ======================================================================================
# SECTION 2: DATA GENERATION AND ANALYSIS FRAMEWORK
# ======================================================================================

# --- 2.1. Realistic Data Generation ---
SDO = Namespace("http://www.example.org/smartphone-data-ontology#")
def generate_realistic_subgraphs(base_dir: str, user_id: int) -> Tuple[Dict[str, str], str]:
    output_dir = os.path.join(base_dir, f"user{user_id}_subgraphs_realistic")
    if os.path.exists(output_dir): shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    print(f"--- Generating realistic dummy data in '{output_dir}' ---")
    ground_truth = {"anchor_1": "Growing", "anchor_2": "Decaying", "anchor_3": "Stable", "anchor_4": "Volatile", "anchor_5": "Shifting"}
    def save_graph(g, anchor_name, day_index):
        date = datetime(2024, 1, 1) + timedelta(days=day_index)
        g.serialize(os.path.join(output_dir, f"{date.strftime('%Y-%m-%d')}_{anchor_name}.ttl"), format="turtle")
    for i in range(8): # Growing
        g = Graph(); g.bind("sdo", SDO)
        for j in range(2 + int(i**1.5)): g.add((SDO.anchor_1, SDO.performs, SDO[f"activity_log_{j}"]))
        save_graph(g, "anchor_1", i)
    for i in range(8): # Decaying
        g = Graph(); g.bind("sdo", SDO)
        for j in range(max(0, 15 - i * 2)): g.add((SDO.anchor_2, SDO.appears_in, SDO[f"scene_{j}"]))
        save_graph(g, "anchor_2", i)
    for i in range(8): # Stable
        g = Graph(); g.bind("sdo", SDO)
        for j in range(5): g.add((SDO.anchor_3, SDO.interacts_with, SDO[f"person_{j}"]))
        g.add((SDO.anchor_3, SDO.performs, SDO[f"activity_log_stable_{i}"]))
        save_graph(g, "anchor_3", i)
    for i in range(8): # Volatile
        g = Graph(); g.bind("sdo", SDO)
        group_id = i % 3
        for j in range(4): g.add((SDO.anchor_4, SDO.interacts_with, SDO[f"person_group_{group_id}_{j}"]))
        save_graph(g, "anchor_4", i)
    for i in range(8): # Shifting
        g = Graph(); g.bind("sdo", SDO)
        if i < 4:
            for j in range(5): g.add((SDO.anchor_5, SDO.appears_in, SDO[f"scene_research_{j}_{i}"]))
        else:
            for j in range(6): g.add((SDO.anchor_5, SDO.interacts_with, SDO[f"person_dev_{j}"]))
        save_graph(g, "anchor_5", i)
    print("--- Realistic data generation complete ---\n")
    return ground_truth, output_dir

# --- 2.2. Base Strategy Class ---
class TrendAnalysisStrategy:
    def __init__(self, name: str): self.name = name
    def analyze(self, graphs: List[nx.Graph]) -> str: raise NotImplementedError
    def _load_graphs(self, folder_path: str) -> Dict[str, List[nx.Graph]]:
        activities = {}
        if not os.path.isdir(folder_path): return {}
        for filename in sorted(os.listdir(folder_path)):
            if not filename.endswith(".ttl"): continue
            match = re.match(r"(\d{4}-\d{2}-\d{2})_(anchor_\d+)\.ttl", filename)
            if not match: continue
            _, anchor_id = match.groups()
            rdf_graph = Graph().parse(os.path.join(folder_path, filename), format="turtle")
            nx_graph = nx.Graph()
            for s, p, o in rdf_graph:
                if not isinstance(o, Literal): nx_graph.add_edge(s, o)
            if anchor_id not in activities: activities[anchor_id] = []
            activities[anchor_id].append(nx_graph)
        return activities

# --- 2.3. Analysis Strategies ---
class StrategyJaccardSize(TrendAnalysisStrategy):
    def __init__(self): super().__init__("Jaccard + Size")
    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"
        size_changes, jaccard_sims = [], []
        for g1, g2 in zip(graphs, graphs[1:]):
            s1, s2 = g1.number_of_nodes(), g2.number_of_nodes()
            if s1 > 0: size_changes.append((s2 - s1) / s1)
            n1, n2 = set(g1.nodes()), set(g2.nodes())
            union = len(n1.union(n2))
            jaccard_sims.append(len(n1.intersection(n2)) / union if union > 0 else 0)
        if not size_changes: return "Insufficient Data"
        avg_size_change, avg_jaccard = np.mean(size_changes), np.mean(jaccard_sims)
        if avg_size_change > 0.15: return "Growing"
        if avg_size_change < -0.15: return "Decaying"
        if avg_jaccard > 0.7: return "Stable"
        if avg_jaccard < 0.2: return "Shifting"
        return "Volatile"

class StrategyTimeSeriesMetrics(TrendAnalysisStrategy):
    def __init__(self): super().__init__("Time Series on Graph Metrics")
    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 3: return "Insufficient Data"
        nodes = [g.number_of_nodes() for g in graphs]
        slope, _, r_val, _, _ = linregress(list(range(len(graphs))), nodes)
        mean_nodes = np.mean(nodes)
        norm_slope = slope / mean_nodes if mean_nodes > 0 else 0
        if r_val**2 > 0.6:
            if norm_slope > 0.05: return "Growing"
            if norm_slope < -0.05: return "Decaying"
        node_variance = np.std(nodes) / mean_nodes if mean_nodes > 0 else 0
        if node_variance < 0.1: return "Stable"
        if node_variance > 0.4: return "Volatile"
        return "Shifting"

class StrategyNode2Vec(TrendAnalysisStrategy):
    def __init__(self, dimensions=16):
        super().__init__("Node2Vec Embedding")
        self.dimensions = dimensions
    def _get_graph_embedding(self, graph: nx.Graph) -> np.ndarray:
        if graph.number_of_nodes() == 0: return np.zeros(self.dimensions)
        n2v = Node2Vec(graph, dimensions=self.dimensions, walk_length=10, num_walks=50, workers=4, quiet=True)
        model = n2v.fit(window=5, min_count=1)
        node_vectors = [model.wv[str(node)] for node in graph.nodes()]
        return np.mean(node_vectors, axis=0) if node_vectors else np.zeros(self.dimensions)
    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"
        embeddings = [self._get_graph_embedding(g) for g in graphs]
        distances = [np.linalg.norm(e1 - e2) for e1, e2 in zip(embeddings, embeddings[1:])]
        avg_dist = np.mean(distances)
        if avg_dist < 0.1: return "Stable"
        if avg_dist > 0.5: return "Shifting"
        nodes = [g.number_of_nodes() for g in graphs]
        slope, _, _, _, _ = linregress(list(range(len(graphs))), nodes)
        norm_slope = slope / np.mean(nodes) if np.mean(nodes) > 0 else 0
        if norm_slope > 0.05: return "Growing"
        if norm_slope < -0.05: return "Decaying"
        return "Volatile"

class StrategyAdvancedEmbedding(TrendAnalysisStrategy):
    def __init__(self, generator: EmbeddingGenerator):
        super().__init__("Advanced Pre-Trained Embedding")
        self.generator = generator
    def _convert_nx_to_hetero(self, g: nx.Graph) -> HeteroData:
        data = HeteroData()
        node_map = {}
        # Heuristically map nx nodes to types and create features
        for node_type in NODE_TYPES:
            node_list = [n for n in g.nodes() if node_type in str(n).lower()]
            if node_list:
                data[node_type].x = torch.randn(len(node_list), NODE_FEATURE_DIM)
                node_map.update({node: i for i, node in enumerate(node_list)})

        # Map edges
        for src, dst in g.edges():
            src_type, dst_type = None, None
            for nt in NODE_TYPES:
                if nt in str(src).lower(): src_type = nt
                if nt in str(dst).lower(): dst_type = nt

            if src_type and dst_type:
                # Find a matching edge type from metadata
                for s, _, d in EDGE_TYPES:
                    if (s == src_type and d == dst_type) or (s == dst_type and d == src_type):
                        edge_type = (src_type, f'related_to_{dst_type}', dst_type)
                        if edge_type not in data.edge_types:
                             data[edge_type].edge_index = torch.empty((2,0), dtype=torch.long)

                        src_idx, dst_idx = node_map.get(src), node_map.get(dst)
                        if src_idx is not None and dst_idx is not None:
                            edge = torch.tensor([[src_idx], [dst_idx]], dtype=torch.long)
                            data[edge_type].edge_index = torch.cat([data[edge_type].edge_index, edge], dim=1)
        return data
    def analyze(self, graphs: List[nx.Graph]) -> str:
        if len(graphs) < 2: return "Insufficient Data"
        embeddings = []
        for g in graphs:
            if g.number_of_nodes() == 0: continue
            hetero_g = self._convert_nx_to_hetero(g)
            # Generate dummy timestamps as the model requires them
            timestamps = list(range(g.number_of_nodes()))
            emb = self.generator.get_embeddings(timestamps, hetero_g)['graph_embedding']
            embeddings.append(emb)

        if len(embeddings) < 2: return "Insufficient Data"
        distances = [np.linalg.norm(e1 - e2) for e1, e2 in zip(embeddings, embeddings[1:])]
        avg_dist = np.mean(distances)
        if avg_dist < 0.01: return "Stable" # Pre-trained models might produce very stable vecs
        if avg_dist > 0.1: return "Shifting"
        nodes = [g.number_of_nodes() for g in graphs]
        slope, _, _, _, _ = linregress(list(range(len(graphs))), nodes)
        norm_slope = slope / np.mean(nodes) if np.mean(nodes) > 0 else 0
        if norm_slope > 0.05: return "Growing"
        if norm_slope < -0.05: return "Decaying"
        return "Volatile"

# --- 2.4. Performance Evaluation ---
def evaluate_performance(strategy_name: str, y_true: List[str], y_pred: List[str], labels: List[str]):
    print(f"\n--- Performance Evaluation for: {strategy_name} ---")
    present_labels = sorted(list(set(y_true) | set(y_pred)))
    print(classification_report(y_true, y_pred, labels=present_labels, zero_division=0))
    cm = confusion_matrix(y_true, y_pred, labels=present_labels)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=present_labels)
    fig, ax = plt.subplots(figsize=(8, 6))
    disp.plot(cmap=plt.cm.Blues, ax=ax, xticks_rotation='vertical')
    plt.title(f"Confusion Matrix for {strategy_name}")
    plt.tight_layout()
    plt.show()

# ======================================================================================
# SECTION 3: MAIN EXECUTION BLOCK
# ======================================================================================

if __name__ == '__main__':
    # Step 1: Create dummy pre-trained models.
    create_dummy_trained_models()

    # Step 2: Generate the realistic dataset for evaluation.
    ground_truth, data_folder = generate_realistic_subgraphs(base_dir="dummy_data_realistic", user_id=1)

    # Step 3: Initialize all strategies, including the advanced one.
    try:
        adv_embedding_generator = EmbeddingGenerator(
            temporal_model_path="dummy_models/temporal_model.pth",
            graph_model_path="dummy_models/graph_model.pth"
        )
        strategies = [
            StrategyJaccardSize(),
            StrategyTimeSeriesMetrics(),
            StrategyNode2Vec(),
            StrategyAdvancedEmbedding(adv_embedding_generator)
        ]
    except (FileNotFoundError, NameError) as e:
        print(f"\nError initializing strategies: {e}")
        print("Skipping advanced model comparison.")
        strategies = [StrategyJaccardSize(), StrategyTimeSeriesMetrics(), StrategyNode2Vec()]

    # Step 4: Run analysis and evaluation for each strategy.
    all_labels = sorted(list(set(ground_truth.values())))

    for strategy in strategies:
        activity_graphs = strategy._load_graphs(data_folder)
        predictions = {}
        print(f"\n--- Running analysis with: {strategy.name} ---")
        for anchor_id, graphs in activity_graphs.items():
            if anchor_id in ground_truth:
                print(f"  Analyzing '{anchor_id}'...")
                predictions[anchor_id] = strategy.analyze(graphs)

        y_true, y_pred = [], []
        for anchor_id, true_label in ground_truth.items():
            if anchor_id in predictions:
                y_true.append(true_label)
                y_pred.append(predictions[anchor_id])

        if y_true:
            evaluate_performance(strategy.name, y_true, y_pred, labels=all_labels)
        else:
            print(f"Could not run evaluation for {strategy.name}.")

